{-# LANGUAGE OverloadedStrings #-}

-- MODULE

module Pllisp.Codegen (codegen) where

import qualified Pllisp.BuiltIn as BuiltIn
import qualified Pllisp.CST as CST
import qualified Pllisp.LambdaLift as LL
import qualified Pllisp.Type as Ty

import Data.Bits ((.|.))
import Control.Monad (forM_, void)
import Control.Monad.State.Strict
import qualified Data.Map.Strict as M
import qualified Data.Set as S
import qualified Data.Text as T

-- TYPES

data CtorInfo = CtorInfo
  { ciTag  :: !Int
  , ciArgs :: [Ty.Type]
  } deriving (Show)

data CgState = CgState
  { csFresh   :: !Int
  , csStrLits :: [(T.Text, T.Text)]       -- (global name, value), reverse order
  , csBlock   :: T.Text                    -- current basic block label
  , csVars    :: M.Map CST.Symbol T.Text   -- pllisp name → LLVM operand
  , csCtors   :: M.Map CST.Symbol CtorInfo -- constructor info from TYPE decls
  , csDefs    :: M.Map CST.Symbol LL.LLDef -- lifted function defs
  , csInstrs  :: [T.Text]                  -- instructions, reverse order
  }

type CgM = State CgState

-- Every struct field is 8-byte aligned for uniform layout
slotSize :: Int
slotSize = 8

-- ENTRY POINT

codegen :: LL.LLProgram -> T.Text
codegen prog = evalState go initState
  where
    ctors    = collectCtors (LL.llExprs prog)
    defMap   = M.fromList [(LL.defName d, d) | d <- LL.llDefs prog]
    initState = CgState 0 [] "entry" M.empty ctors defMap []

    go :: CgM T.Text
    go = do
      defTexts <- mapM genDef (LL.llDefs prog)
      mainText <- genMain (LL.llExprs prog)
      strLits  <- gets (reverse . csStrLits)
      let strDecls = map genStrDecl strLits
      pure $ T.unlines $
        [ moduleHeader, "" ]
        ++ [ externDecls ]
        ++ [ fmtConstants ]
        ++ strDecls
        ++ [ "" ]
        ++ [ rxHelperDefs ]
        ++ defTexts
        ++ [ mainText ]

-- MODULE-LEVEL DECLARATIONS

moduleHeader :: T.Text
moduleHeader = "; Generated by pllisp"

externDecls :: T.Text
externDecls = T.unlines
  [ "declare ptr @malloc(i64)"
  , "declare void @free(ptr)"
  , "declare i32 @puts(ptr)"
  , "declare i64 @strlen(ptr)"
  , "declare i32 @strcmp(ptr, ptr)"
  , "declare ptr @strcpy(ptr, ptr)"
  , "declare ptr @strcat(ptr, ptr)"
  , "declare ptr @strstr(ptr, ptr)"
  , "declare ptr @memcpy(ptr, ptr, i64)"
  , "declare i32 @snprintf(ptr, i64, ptr, ...)"
  , "declare ptr @fgets(ptr, i32, ptr)"
  , "declare i32 @feof(ptr)"
  , "@stdin = external global ptr"
  , "@__argc = private global i32 0"
  , "@__argv = private global ptr null"
  , "declare ptr @realloc(ptr, i64)"
  -- PCRE2 (8-bit)
  , "declare ptr @pcre2_compile_8(ptr, i64, i32, ptr, ptr, ptr)"
  , "declare ptr @pcre2_match_data_create_from_pattern_8(ptr, ptr)"
  , "declare i32 @pcre2_match_8(ptr, ptr, i64, i64, i32, ptr, ptr)"
  , "declare ptr @pcre2_get_ovector_pointer_8(ptr)"
  , "declare i32 @pcre2_get_ovector_count_8(ptr)"
  , "declare void @pcre2_match_data_free_8(ptr)"
  , "declare void @pcre2_code_free_8(ptr)"
  , "declare i32 @pcre2_substitute_8(ptr, ptr, i64, i64, i32, ptr, ptr, ptr, i64, ptr, ptr)"
  , "declare void @llvm.memcpy.p0.p0.i64(ptr, ptr, i64, i1)"
  ]

fmtConstants :: T.Text
fmtConstants = T.unlines
  [ "@fmt.int = private unnamed_addr constant [4 x i8] c\"%ld\\00\""
  , "@fmt.flt = private unnamed_addr constant [3 x i8] c\"%g\\00\""
  ]

genStrDecl :: (T.Text, T.Text) -> T.Text
genStrDecl (name, value) =
  let escaped = escapeForLLVM value
      len = T.length value + 1  -- +1 for null terminator
  in "@" <> name <> " = private unnamed_addr constant ["
     <> tshow len <> " x i8] c\"" <> escaped <> "\\00\""

escapeForLLVM :: T.Text -> T.Text
escapeForLLVM = T.concatMap escChar
  where
    escChar '\\' = "\\\\"
    escChar '"'  = "\\22"
    escChar '\n' = "\\0A"
    escChar '\t' = "\\09"
    escChar c    = T.singleton c

-- TYPE INFO COLLECTION

collectCtors :: [LL.LLExpr] -> M.Map CST.Symbol CtorInfo
collectCtors = foldl' go M.empty
  where
    go acc (Ty.Typed _ (LL.LLType _ _ dataCons)) =
      foldl' addCtor acc (zip [0..] dataCons)
    go acc _ = acc
    addCtor acc (tag, CST.DataCon name fields) =
      M.insert name (CtorInfo tag fields) acc

-- LLVM TYPE MAPPING

llvmType :: Ty.Type -> T.Text
llvmType Ty.TyInt       = "i64"
llvmType Ty.TyFlt       = "double"
llvmType Ty.TyStr       = "ptr"
llvmType Ty.TyBool      = "i1"
llvmType Ty.TyUnit      = "i8"
llvmType Ty.TyRx     = "ptr"
llvmType (Ty.TyFun _ _) = "ptr"
llvmType (Ty.TyCon _ _) = "ptr"
llvmType (Ty.TyVar _)   = "ptr"

-- STATE HELPERS

fresh :: CgM T.Text
fresh = do
  n <- gets csFresh
  modify' (\s -> s { csFresh = n + 1 })
  pure ("%t" <> tshow n)

freshLabel :: T.Text -> CgM T.Text
freshLabel prefix = do
  n <- gets csFresh
  modify' (\s -> s { csFresh = n + 1 })
  pure (prefix <> "." <> tshow n)

emit :: T.Text -> CgM ()
emit line = modify' (\s -> s { csInstrs = ("  " <> line) : csInstrs s })

emitLabel :: T.Text -> CgM ()
emitLabel lbl =
  modify' (\s -> s { csInstrs = (lbl <> ":") : csInstrs s, csBlock = lbl })

addStrLit :: T.Text -> CgM T.Text
addStrLit value = do
  lits <- gets csStrLits
  case lookup value [(v, n) | (n, v) <- lits] of
    Just name -> pure ("@" <> name)
    Nothing -> do
      let name = "str." <> tshow (length lits)
      modify' (\s -> s { csStrLits = (name, value) : csStrLits s })
      pure ("@" <> name)

bindVar :: CST.Symbol -> T.Text -> CgM ()
bindVar name op = modify' (\s -> s { csVars = M.insert name op (csVars s) })

lookupVar :: CST.Symbol -> CgM T.Text
lookupVar name = do
  vars <- gets csVars
  case M.lookup name vars of
    Just op -> pure op
    Nothing -> do
      ctors <- gets csCtors
      case M.lookup name ctors of
        Just ci | null (ciArgs ci) -> genCtorAlloc ci []
        _ -> error ("Codegen: unbound variable: " <> T.unpack name)

tshow :: Show a => a -> T.Text
tshow = T.pack . show

sanitize :: T.Text -> T.Text
sanitize = T.concatMap (\c -> if c == '-' then "_" else T.singleton c)

-- FUNCTION GENERATION

genDef :: LL.LLDef -> CgM T.Text
genDef def = do
  savedVars   <- gets csVars
  savedInstrs <- gets csInstrs
  savedBlock  <- gets csBlock
  modify' (\s -> s { csVars = M.empty, csInstrs = [], csBlock = "entry" })

  -- Bind regular params
  forM_ (LL.defParams def) $ \(pname, _) ->
    bindVar pname ("%" <> sanitize pname)

  -- Unpack env from closure pointer
  forM_ (zip [0..] (LL.defEnv def)) $ \(i, (ename, ety)) -> do
    let offset = slotSize * (i + 1)  -- skip fnptr at offset 0
    ptr <- fresh
    val <- fresh
    emit (ptr <> " = getelementptr i8, ptr %__closure, i64 " <> tshow offset)
    emit (val <> " = load " <> llvmType ety <> ", ptr " <> ptr)
    bindVar ename val

  -- Generate body and return
  result <- genExpr (LL.defBody def)
  let retTy = LL.defRetTy def
  emit ("ret " <> llvmType retTy <> " " <> result)

  instrs <- gets (reverse . csInstrs)
  modify' (\s -> s { csVars = savedVars, csInstrs = savedInstrs, csBlock = savedBlock })

  let paramList = "ptr %__closure" <>
        T.concat [", " <> llvmType pty <> " %" <> sanitize pname
                 | (pname, pty) <- LL.defParams def]

  pure $ T.unlines $
    [ "define " <> llvmType retTy <> " @" <> sanitize (LL.defName def)
      <> "(" <> paramList <> ") {"
    , "entry:" ]
    ++ instrs
    ++ [ "}", "" ]

genMain :: [LL.LLExpr] -> CgM T.Text
genMain exprs = do
  savedVars   <- gets csVars
  savedInstrs <- gets csInstrs
  savedBlock  <- gets csBlock
  modify' (\s -> s { csVars = M.empty, csInstrs = [], csBlock = "entry" })

  -- Store argc/argv into globals
  emit "store i32 %argc, ptr @__argc"
  emit "store ptr %argv, ptr @__argv"

  mapM_ genTopExpr exprs
  emit "ret i32 0"

  instrs <- gets (reverse . csInstrs)
  modify' (\s -> s { csVars = savedVars, csInstrs = savedInstrs, csBlock = savedBlock })

  pure $ T.unlines $
    [ "define i32 @main(i32 %argc, ptr %argv) {"
    , "entry:" ]
    ++ instrs
    ++ [ "}" ]

genTopExpr :: LL.LLExpr -> CgM ()
genTopExpr (Ty.Typed _ (LL.LLType {})) = pure ()
genTopExpr expr = void (genExpr expr)

-- EXPRESSION GENERATION

genExpr :: LL.LLExpr -> CgM T.Text
genExpr (Ty.Typed t expr) = case expr of
  LL.LLLit lit   -> genLit lit
  LL.LLBool b    -> pure (if b then "1" else "0")
  LL.LLUnit      -> pure "0"
  LL.LLVar name _ -> lookupVar name

  LL.LLLet binds body -> do
    savedVars <- gets csVars
    -- Pass 1: pre-allocate closures so recursive references work
    forM_ binds $ \(name, _, rhs) -> case Ty.val rhs of
      LL.LLMkClosure _ envArgs -> do
        let totalSize = slotSize * (1 + length envArgs)
        closure <- fresh
        emit (closure <> " = call ptr @malloc(i64 " <> tshow totalSize <> ")")
        bindVar name closure
      _ -> pure ()
    -- Pass 2: fill in closures and generate other bindings
    forM_ binds $ \(name, _, rhs) -> case Ty.val rhs of
      LL.LLMkClosure fnName envArgs -> do
        closure <- lookupVar name
        fillClosure closure fnName envArgs
      _ -> do
        op <- genExpr rhs
        bindVar name op
    result <- genExpr body
    modify' (\s -> s { csVars = savedVars })
    pure result

  LL.LLIf cond thenE elseE -> genIf t cond thenE elseE
  LL.LLApp func args       -> genApp t func args
  LL.LLMkClosure name envs -> genMkClosure name envs
  LL.LLCase scr arms       -> genCase t scr arms
  LL.LLType {}             -> pure "0"

genLit :: CST.Literal -> CgM T.Text
genLit (CST.LitInt n) = pure (tshow n)
genLit (CST.LitFlt f) = pure (T.pack (showFlt f))
genLit (CST.LitStr s) = addStrLit s
genLit (CST.LitRx pat flags) = do
  patPtr <- addStrLit pat
  let compileOpts = flagsToCompileOpts flags
  -- pcre2_compile_8(pattern, PCRE2_ZERO_TERMINATED, options, &errcode, &erroffset, NULL)
  errcode <- fresh
  emit (errcode <> " = alloca i32")
  erroff <- fresh
  emit (erroff <> " = alloca i64")
  compiled <- fresh
  emit (compiled <> " = call ptr @pcre2_compile_8(ptr " <> patPtr
    <> ", i64 -1, i32 " <> tshow compileOpts
    <> ", ptr " <> errcode <> ", ptr " <> erroff <> ", ptr null)")
  pure compiled

flagsToCompileOpts :: T.Text -> Int
flagsToCompileOpts = T.foldl' addFlag 0
  where
    addFlag acc 'i' = acc .|. 0x8    -- PCRE2_CASELESS
    addFlag acc 'm' = acc .|. 0x400  -- PCRE2_MULTILINE
    addFlag acc 's' = acc .|. 0x20   -- PCRE2_DOTALL
    addFlag acc 'x' = acc .|. 0x80   -- PCRE2_EXTENDED
    addFlag acc _   = acc            -- unknown flags (e.g. 'g') ignored

showFlt :: Double -> String
showFlt f =
  let s = show f
  in if '.' `elem` s || 'e' `elem` s || 'E' `elem` s then s else s ++ ".0"

-- IF/THEN/ELSE

genIf :: Ty.Type -> LL.LLExpr -> LL.LLExpr -> LL.LLExpr -> CgM T.Text
genIf resTy cond thenE elseE = do
  condOp   <- genExpr cond
  thenLbl  <- freshLabel "then"
  elseLbl  <- freshLabel "else"
  mergeLbl <- freshLabel "merge"

  emit ("br i1 " <> condOp <> ", label %" <> thenLbl <> ", label %" <> elseLbl)

  emitLabel thenLbl
  thenOp   <- genExpr thenE
  thenExit <- gets csBlock
  emit ("br label %" <> mergeLbl)

  emitLabel elseLbl
  elseOp   <- genExpr elseE
  elseExit <- gets csBlock
  emit ("br label %" <> mergeLbl)

  emitLabel mergeLbl
  result <- fresh
  emit (result <> " = phi " <> llvmType resTy
    <> " [" <> thenOp <> ", %" <> thenExit <> "]"
    <> ", [" <> elseOp <> ", %" <> elseExit <> "]")
  pure result

-- APPLICATION

genApp :: Ty.Type -> LL.LLExpr -> [LL.LLExpr] -> CgM T.Text
genApp resTy func args = do
  argResults <- mapM (\a -> do op <- genExpr a; pure (Ty.ty a, op)) args
  ctors <- gets csCtors

  case Ty.val func of
    LL.LLVar name _ | S.member name BuiltIn.builtInNames ->
      genBuiltIn name argResults resTy
    LL.LLVar name _ | M.member name ctors ->
      genCtorAlloc (ctors M.! name) argResults
    _ -> do
      closureOp <- genExpr func
      genClosureCall closureOp argResults resTy

-- CLOSURE OPERATIONS

genMkClosure :: CST.Symbol -> [LL.LLExpr] -> CgM T.Text
genMkClosure name envArgs = do
  let totalSize = slotSize * (1 + length envArgs)
  closure <- fresh
  emit (closure <> " = call ptr @malloc(i64 " <> tshow totalSize <> ")")
  fillClosure closure name envArgs
  pure closure

fillClosure :: T.Text -> CST.Symbol -> [LL.LLExpr] -> CgM ()
fillClosure closure name envArgs = do
  emit ("store ptr @" <> sanitize name <> ", ptr " <> closure)
  forM_ (zip [1..] envArgs) $ \(i, envExpr) -> do
    envOp <- genExpr envExpr
    ptr <- fresh
    emit (ptr <> " = getelementptr i8, ptr " <> closure
      <> ", i64 " <> tshow (slotSize * (i :: Int)))
    emit ("store " <> llvmType (Ty.ty envExpr) <> " " <> envOp <> ", ptr " <> ptr)

genClosureCall :: T.Text -> [(Ty.Type, T.Text)] -> Ty.Type -> CgM T.Text
genClosureCall closureOp argResults resTy = do
  fnptr <- fresh
  emit (fnptr <> " = load ptr, ptr " <> closureOp)

  let argList = "ptr " <> closureOp <>
        T.concat [", " <> llvmType t <> " " <> op | (t, op) <- argResults]

  result <- fresh
  emit (result <> " = call " <> llvmType resTy <> " "
    <> fnptr <> "(" <> argList <> ")")
  pure result

-- CONSTRUCTOR OPERATIONS

genCtorAlloc :: CtorInfo -> [(Ty.Type, T.Text)] -> CgM T.Text
genCtorAlloc ci args = do
  let totalSize = slotSize * (1 + length args)
  obj <- fresh
  emit (obj <> " = call ptr @malloc(i64 " <> tshow totalSize <> ")")

  -- Store tag at offset 0
  emit ("store i32 " <> tshow (ciTag ci) <> ", ptr " <> obj)

  -- Store fields at subsequent offsets
  forM_ (zip [1..] args) $ \(i, (argTy, argOp)) -> do
    ptr <- fresh
    emit (ptr <> " = getelementptr i8, ptr " <> obj
      <> ", i64 " <> tshow (slotSize * (i :: Int)))
    emit ("store " <> llvmType argTy <> " " <> argOp <> ", ptr " <> ptr)

  pure obj

-- CASE EXPRESSIONS

genCase :: Ty.Type -> LL.LLExpr -> [(LL.LLPattern, LL.LLExpr)] -> CgM T.Text
genCase resTy scr arms = do
  scrOp    <- genExpr scr
  mergeLbl <- freshLabel "case.merge"
  phiPairs <- genArms scrOp arms mergeLbl

  emitLabel mergeLbl
  if null phiPairs
    then do
      emit "unreachable"
      pure "0"
    else do
      result <- fresh
      let phiArgs = T.intercalate ", "
            ["[" <> op <> ", %" <> lbl <> "]" | (op, lbl) <- phiPairs]
      emit (result <> " = phi " <> llvmType resTy <> " " <> phiArgs)
      pure result

genArms :: T.Text -> [(LL.LLPattern, LL.LLExpr)] -> T.Text -> CgM [(T.Text, T.Text)]
genArms _ [] _ = do
  emit "unreachable"
  pure []
genArms scrOp ((pat, body):rest) mergeLbl = case pat of
  LL.LLPatWild _ -> genCatchAllArm scrOp pat body mergeLbl
  LL.LLPatVar {} -> genCatchAllArm scrOp pat body mergeLbl
  _ -> do
    matchLbl <- freshLabel "case.match"
    nextLbl  <- freshLabel "case.next"
    genPatTest scrOp pat matchLbl nextLbl

    emitLabel matchLbl
    savedVars <- gets csVars
    bindPatVars scrOp pat
    bodyOp   <- genExpr body
    bodyExit <- gets csBlock
    emit ("br label %" <> mergeLbl)
    modify' (\s -> s { csVars = savedVars })

    emitLabel nextLbl
    restPairs <- genArms scrOp rest mergeLbl
    pure ((bodyOp, bodyExit) : restPairs)

genCatchAllArm :: T.Text -> LL.LLPattern -> LL.LLExpr -> T.Text -> CgM [(T.Text, T.Text)]
genCatchAllArm scrOp pat body mergeLbl = do
  savedVars <- gets csVars
  case pat of
    LL.LLPatVar name _ -> bindVar name scrOp
    _                  -> pure ()
  bodyOp   <- genExpr body
  bodyExit <- gets csBlock
  emit ("br label %" <> mergeLbl)
  modify' (\s -> s { csVars = savedVars })
  pure [(bodyOp, bodyExit)]

genPatTest :: T.Text -> LL.LLPattern -> T.Text -> T.Text -> CgM ()
genPatTest scrOp pat matchLbl nextLbl = case pat of
  LL.LLPatBool b -> do
    cmp <- fresh
    emit (cmp <> " = icmp eq i1 " <> scrOp <> ", " <> if b then "1" else "0")
    emit ("br i1 " <> cmp <> ", label %" <> matchLbl <> ", label %" <> nextLbl)

  LL.LLPatLit (CST.LitInt n) -> do
    cmp <- fresh
    emit (cmp <> " = icmp eq i64 " <> scrOp <> ", " <> tshow n)
    emit ("br i1 " <> cmp <> ", label %" <> matchLbl <> ", label %" <> nextLbl)

  LL.LLPatLit (CST.LitFlt f) -> do
    cmp <- fresh
    emit (cmp <> " = fcmp oeq double " <> scrOp <> ", " <> T.pack (showFlt f))
    emit ("br i1 " <> cmp <> ", label %" <> matchLbl <> ", label %" <> nextLbl)

  LL.LLPatLit (CST.LitStr s) -> do
    strPtr <- addStrLit s
    cmpR   <- fresh
    emit (cmpR <> " = call i32 @strcmp(ptr " <> scrOp <> ", ptr " <> strPtr <> ")")
    cmp <- fresh
    emit (cmp <> " = icmp eq i32 " <> cmpR <> ", 0")
    emit ("br i1 " <> cmp <> ", label %" <> matchLbl <> ", label %" <> nextLbl)

  LL.LLPatCon ctorName _ _ -> do
    ctors <- gets csCtors
    let ci = ctors M.! ctorName
    tagR <- fresh
    emit (tagR <> " = load i32, ptr " <> scrOp)
    cmp <- fresh
    emit (cmp <> " = icmp eq i32 " <> tagR <> ", " <> tshow (ciTag ci))
    emit ("br i1 " <> cmp <> ", label %" <> matchLbl <> ", label %" <> nextLbl)

  -- Wildcard/var handled in genArms before reaching here
  _ -> emit ("br label %" <> matchLbl)

bindPatVars :: T.Text -> LL.LLPattern -> CgM ()
bindPatVars scrOp pat = case pat of
  LL.LLPatCon _ _ subPats ->
    forM_ (zip [1..] subPats) $ \(i, subPat) -> do
      let offset = slotSize * (i :: Int)
      fieldPtr <- fresh
      emit (fieldPtr <> " = getelementptr i8, ptr " <> scrOp
        <> ", i64 " <> tshow offset)
      let fty = patType subPat
      fieldVal <- fresh
      emit (fieldVal <> " = load " <> llvmType fty <> ", ptr " <> fieldPtr)
      case subPat of
        LL.LLPatVar name _ -> bindVar name fieldVal
        _                  -> pure ()
  LL.LLPatVar name _ -> bindVar name scrOp
  _ -> pure ()

patType :: LL.LLPattern -> Ty.Type
patType (LL.LLPatLit (CST.LitInt _)) = Ty.TyInt
patType (LL.LLPatLit (CST.LitFlt _)) = Ty.TyFlt
patType (LL.LLPatLit (CST.LitStr _)) = Ty.TyStr
patType (LL.LLPatBool _)             = Ty.TyBool
patType (LL.LLPatVar _ ty)           = ty
patType (LL.LLPatWild ty)            = ty
patType (LL.LLPatCon _ ty _)         = ty

-- BUILT-IN FUNCTIONS

genBuiltIn :: CST.Symbol -> [(Ty.Type, T.Text)] -> Ty.Type -> CgM T.Text
genBuiltIn name args _resTy = case name of
  -- Int arithmetic
  "ADD" -> intBinOp "add" args
  "SUB" -> intBinOp "sub" args
  "MUL" -> intBinOp "mul" args
  "DIV" -> intBinOp "sdiv" args
  "MOD" -> intBinOp "srem" args
  "NEG" -> do
    let (_, op) = head args
    r <- fresh
    emit (r <> " = sub i64 0, " <> op)
    pure r

  -- Float arithmetic
  "ADDF" -> fltBinOp "fadd" args
  "SUBF" -> fltBinOp "fsub" args
  "MULF" -> fltBinOp "fmul" args
  "DIVF" -> fltBinOp "fdiv" args
  "NEGF" -> do
    let (_, op) = head args
    r <- fresh
    emit (r <> " = fsub double 0.0, " <> op)
    pure r

  -- Int comparison
  "EQ" -> intCmp "eq" args
  "LT" -> intCmp "slt" args
  "GT" -> intCmp "sgt" args
  "LE" -> intCmp "sle" args
  "GE" -> intCmp "sge" args

  -- Float comparison
  "EQF" -> fltCmp "oeq" args
  "LTF" -> fltCmp "olt" args
  "GTF" -> fltCmp "ogt" args
  "LEF" -> fltCmp "ole" args
  "GEF" -> fltCmp "oge" args

  -- Boolean
  "AND" -> do
    let [(_, a), (_, b)] = args
    r <- fresh
    emit (r <> " = and i1 " <> a <> ", " <> b)
    pure r
  "OR" -> do
    let [(_, a), (_, b)] = args
    r <- fresh
    emit (r <> " = or i1 " <> a <> ", " <> b)
    pure r
  "NOT" -> do
    let [(_, op)] = args
    r <- fresh
    emit (r <> " = xor i1 " <> op <> ", 1")
    pure r

  -- String comparison
  "EQS" -> do
    let [(_, s1), (_, s2)] = args
    cmpR <- fresh
    emit (cmpR <> " = call i32 @strcmp(ptr " <> s1 <> ", ptr " <> s2 <> ")")
    r <- fresh
    emit (r <> " = icmp eq i32 " <> cmpR <> ", 0")
    pure r

  -- String operations
  "CONCAT" -> do
    let [(_, s1), (_, s2)] = args
    len1 <- fresh
    emit (len1 <> " = call i64 @strlen(ptr " <> s1 <> ")")
    len2 <- fresh
    emit (len2 <> " = call i64 @strlen(ptr " <> s2 <> ")")
    total <- fresh
    emit (total <> " = add i64 " <> len1 <> ", " <> len2)
    total1 <- fresh
    emit (total1 <> " = add i64 " <> total <> ", 1")
    buf <- fresh
    emit (buf <> " = call ptr @malloc(i64 " <> total1 <> ")")
    d1 <- fresh
    emit (d1 <> " = call ptr @strcpy(ptr " <> buf <> ", ptr " <> s1 <> ")")
    d2 <- fresh
    emit (d2 <> " = call ptr @strcat(ptr " <> buf <> ", ptr " <> s2 <> ")")
    pure buf

  "STRLEN" -> do
    let [(_, s)] = args
    r <- fresh
    emit (r <> " = call i64 @strlen(ptr " <> s <> ")")
    pure r

  "SUBSTR" -> do
    let [(_, s), (_, start), (_, len)] = args
    buf <- fresh
    len1 <- fresh
    emit (len1 <> " = add i64 " <> len <> ", 1")
    emit (buf <> " = call ptr @malloc(i64 " <> len1 <> ")")
    srcPtr <- fresh
    emit (srcPtr <> " = getelementptr i8, ptr " <> s <> ", i64 " <> start)
    d <- fresh
    emit (d <> " = call ptr @memcpy(ptr " <> buf <> ", ptr " <> srcPtr <> ", i64 " <> len <> ")")
    -- Null-terminate
    termPtr <- fresh
    emit (termPtr <> " = getelementptr i8, ptr " <> buf <> ", i64 " <> len)
    emit ("store i8 0, ptr " <> termPtr)
    pure buf

  "STR-CONTAINS" -> do
    let [(_, haystack), (_, needle)] = args
    result <- fresh
    emit (result <> " = call ptr @strstr(ptr " <> haystack <> ", ptr " <> needle <> ")")
    r <- fresh
    emit (r <> " = icmp ne ptr " <> result <> ", null")
    pure r

  -- IO
  "PRINT" -> do
    let [(_, s)] = args
    d <- fresh
    emit (d <> " = call i32 @puts(ptr " <> s <> ")")
    pure "0"

  "READ-LINE" -> do
    buf <- fresh
    emit (buf <> " = call ptr @malloc(i64 1024)")
    stdinVal <- fresh
    emit (stdinVal <> " = load ptr, ptr @stdin")
    d <- fresh
    emit (d <> " = call ptr @fgets(ptr " <> buf <> ", i32 1024, ptr " <> stdinVal <> ")")
    -- Check for EOF (fgets returns null)
    isNull <- fresh
    emit (isNull <> " = icmp eq ptr " <> d <> ", null")
    eofLbl <- freshLabel "readline.eof"
    okLbl  <- freshLabel "readline.ok"
    doneLbl <- freshLabel "readline.done"
    emit ("br i1 " <> isNull <> ", label %" <> eofLbl <> ", label %" <> okLbl)
    -- EOF: null-terminate at position 0
    emitLabel eofLbl
    emit ("store i8 0, ptr " <> buf)
    emit ("br label %" <> doneLbl)
    -- OK: strip trailing newline
    emitLabel okLbl
    len <- fresh
    emit (len <> " = call i64 @strlen(ptr " <> buf <> ")")
    hasChars <- fresh
    emit (hasChars <> " = icmp sgt i64 " <> len <> ", 0")
    stripLbl <- freshLabel "readline.strip"
    emit ("br i1 " <> hasChars <> ", label %" <> stripLbl <> ", label %" <> doneLbl)
    emitLabel stripLbl
    lenM1 <- fresh
    emit (lenM1 <> " = sub i64 " <> len <> ", 1")
    lastPtr <- fresh
    emit (lastPtr <> " = getelementptr i8, ptr " <> buf <> ", i64 " <> lenM1)
    lastChar <- fresh
    emit (lastChar <> " = load i8, ptr " <> lastPtr)
    isNl <- fresh
    emit (isNl <> " = icmp eq i8 " <> lastChar <> ", 10")
    nlLbl <- freshLabel "readline.nl"
    emit ("br i1 " <> isNl <> ", label %" <> nlLbl <> ", label %" <> doneLbl)
    emitLabel nlLbl
    emit ("store i8 0, ptr " <> lastPtr)
    emit ("br label %" <> doneLbl)
    emitLabel doneLbl
    pure buf

  "IS-EOF" -> do
    stdinVal <- fresh
    emit (stdinVal <> " = load ptr, ptr @stdin")
    r <- fresh
    emit (r <> " = call i32 @feof(ptr " <> stdinVal <> ")")
    result <- fresh
    emit (result <> " = icmp ne i32 " <> r <> ", 0")
    pure result

  -- CLI
  "ARGC" -> do
    r <- fresh
    emit (r <> " = load i32, ptr @__argc")
    result <- fresh
    emit (result <> " = sext i32 " <> r <> " to i64")
    pure result

  "ARGV" -> do
    let [(_, idx)] = args
    argvPtr <- fresh
    emit (argvPtr <> " = load ptr, ptr @__argv")
    elemPtr <- fresh
    emit (elemPtr <> " = getelementptr ptr, ptr " <> argvPtr <> ", i64 " <> idx)
    r <- fresh
    emit (r <> " = load ptr, ptr " <> elemPtr)
    pure r

  -- Conversion
  "INT-TO-FLT" -> do
    let [(_, op)] = args
    r <- fresh
    emit (r <> " = sitofp i64 " <> op <> " to double")
    pure r

  "FLT-TO-INT" -> do
    let [(_, op)] = args
    r <- fresh
    emit (r <> " = fptosi double " <> op <> " to i64")
    pure r

  "INT-TO-STR" -> do
    let [(_, op)] = args
    buf <- fresh
    emit (buf <> " = call ptr @malloc(i64 21)")
    d <- fresh
    emit (d <> " = call i32 (ptr, i64, ptr, ...) @snprintf(ptr " <> buf
      <> ", i64 21, ptr @fmt.int, i64 " <> op <> ")")
    pure buf

  "FLT-TO-STR" -> do
    let [(_, op)] = args
    buf <- fresh
    emit (buf <> " = call ptr @malloc(i64 32)")
    d <- fresh
    emit (d <> " = call i32 (ptr, i64, ptr, ...) @snprintf(ptr " <> buf
      <> ", i64 32, ptr @fmt.flt, double " <> op <> ")")
    pure buf

  -- Rx
  "RX-MATCH" -> do
    let [(_, pat), (_, subj)] = args
    r <- fresh
    emit (r <> " = call i32 @pll_rx_match(ptr " <> pat <> ", ptr " <> subj <> ")")
    result <- fresh
    emit (result <> " = icmp ne i32 " <> r <> ", 0")
    pure result

  "RX-FIND" -> do
    let [(_, pat), (_, subj)] = args
    r <- fresh
    emit (r <> " = call ptr @pll_rx_find(ptr " <> pat <> ", ptr " <> subj <> ")")
    pure r

  "RX-SUB" -> do
    let [(_, pat), (_, repl), (_, subj)] = args
    r <- fresh
    emit (r <> " = call ptr @pll_rx_sub(ptr " <> pat <> ", ptr " <> repl <> ", ptr " <> subj <> ")")
    pure r

  "RX-GSUB" -> do
    let [(_, pat), (_, repl), (_, subj)] = args
    r <- fresh
    emit (r <> " = call ptr @pll_rx_gsub(ptr " <> pat <> ", ptr " <> repl <> ", ptr " <> subj <> ")")
    pure r

  "RX-SPLIT" -> do
    let [(_, pat), (_, subj)] = args
    r <- fresh
    emit (r <> " = call ptr @pll_rx_split(ptr " <> pat <> ", ptr " <> subj <> ")")
    pure r

  "RX-CAPTURES" -> do
    let [(_, pat), (_, subj)] = args
    r <- fresh
    emit (r <> " = call ptr @pll_rx_captures(ptr " <> pat <> ", ptr " <> subj <> ")")
    pure r

  "RX-COMPILE" -> do
    let [(_, s)] = args
    errcode <- fresh
    emit (errcode <> " = alloca i32")
    erroff <- fresh
    emit (erroff <> " = alloca i64")
    compiled <- fresh
    emit (compiled <> " = call ptr @pcre2_compile_8(ptr " <> s
      <> ", i64 -1, i32 0"
      <> ", ptr " <> errcode <> ", ptr " <> erroff <> ", ptr null)")
    pure compiled

  _ -> error ("Codegen: unknown built-in: " <> T.unpack name)

-- Helpers for binary ops

intBinOp :: T.Text -> [(Ty.Type, T.Text)] -> CgM T.Text
intBinOp op [(_, a), (_, b)] = do
  r <- fresh; emit (r <> " = " <> op <> " i64 " <> a <> ", " <> b); pure r
intBinOp _ _ = error "intBinOp: expected 2 args"

fltBinOp :: T.Text -> [(Ty.Type, T.Text)] -> CgM T.Text
fltBinOp op [(_, a), (_, b)] = do
  r <- fresh; emit (r <> " = " <> op <> " double " <> a <> ", " <> b); pure r
fltBinOp _ _ = error "fltBinOp: expected 2 args"

intCmp :: T.Text -> [(Ty.Type, T.Text)] -> CgM T.Text
intCmp p [(_, a), (_, b)] = do
  r <- fresh; emit (r <> " = icmp " <> p <> " i64 " <> a <> ", " <> b); pure r
intCmp _ _ = error "intCmp: expected 2 args"

fltCmp :: T.Text -> [(Ty.Type, T.Text)] -> CgM T.Text
fltCmp p [(_, a), (_, b)] = do
  r <- fresh; emit (r <> " = fcmp " <> p <> " double " <> a <> ", " <> b); pure r
fltCmp _ _ = error "fltCmp: expected 2 args"

-- RX HELPER FUNCTIONS (embedded LLVM IR)
-- These implement the 6 rx built-ins using PCRE2, defined as functions
-- within the generated module so we don't need a separate C file.
-- All helpers receive a pre-compiled PCRE2 rx (ptr) as first argument.

rxHelperDefs :: T.Text
rxHelperDefs = T.unlines
  -- pll_rx_match: does compiled rx match subject? returns i32 (0/1)
  [ "define i32 @pll_rx_match(ptr %re, ptr %subj) {"
  , "entry:"
  , "  %null = icmp eq ptr %re, null"
  , "  br i1 %null, label %fail, label %try"
  , "try:"
  , "  %md = call ptr @pcre2_match_data_create_from_pattern_8(ptr %re, ptr null)"
  , "  %rc = call i32 @pcre2_match_8(ptr %re, ptr %subj, i64 -1, i64 0, i32 0, ptr %md, ptr null)"
  , "  call void @pcre2_match_data_free_8(ptr %md)"
  , "  %ok = icmp sgt i32 %rc, -1"
  , "  %r = zext i1 %ok to i32"
  , "  br label %done"
  , "fail:"
  , "  br label %done"
  , "done:"
  , "  %ret = phi i32 [ %r, %try ], [ 0, %fail ]"
  , "  ret i32 %ret"
  , "}"
  , ""
  -- pll_rx_find: first match as new string, or ""
  , "define ptr @pll_rx_find(ptr %re, ptr %subj) {"
  , "entry:"
  , "  %null = icmp eq ptr %re, null"
  , "  br i1 %null, label %nomatch, label %try"
  , "try:"
  , "  %md = call ptr @pcre2_match_data_create_from_pattern_8(ptr %re, ptr null)"
  , "  %rc = call i32 @pcre2_match_8(ptr %re, ptr %subj, i64 -1, i64 0, i32 0, ptr %md, ptr null)"
  , "  %miss = icmp slt i32 %rc, 0"
  , "  br i1 %miss, label %nomatch.md, label %hit"
  , "nomatch.md:"
  , "  call void @pcre2_match_data_free_8(ptr %md)"
  , "  br label %nomatch"
  , "nomatch:"
  , "  %e0 = call ptr @malloc(i64 1)"
  , "  store i8 0, ptr %e0"
  , "  ret ptr %e0"
  , "hit:"
  , "  %ov = call ptr @pcre2_get_ovector_pointer_8(ptr %md)"
  , "  %s = load i64, ptr %ov"
  , "  %ep = getelementptr i64, ptr %ov, i32 1"
  , "  %e = load i64, ptr %ep"
  , "  %len = sub i64 %e, %s"
  , "  %len1 = add i64 %len, 1"
  , "  %buf = call ptr @malloc(i64 %len1)"
  , "  %src = getelementptr i8, ptr %subj, i64 %s"
  , "  call void @llvm.memcpy.p0.p0.i64(ptr %buf, ptr %src, i64 %len, i1 false)"
  , "  %term = getelementptr i8, ptr %buf, i64 %len"
  , "  store i8 0, ptr %term"
  , "  call void @pcre2_match_data_free_8(ptr %md)"
  , "  ret ptr %buf"
  , "}"
  , ""
  -- pll_rx_sub: replace first
  , "define ptr @pll_rx_sub(ptr %re, ptr %repl, ptr %subj) {"
  , "entry:"
  , "  %null = icmp eq ptr %re, null"
  , "  br i1 %null, label %copyret, label %comp.ok"
  , "copyret:"
  , "  %sl0 = call i64 @strlen(ptr %subj)"
  , "  %sl01 = add i64 %sl0, 1"
  , "  %cp0 = call ptr @malloc(i64 %sl01)"
  , "  %_d0 = call ptr @strcpy(ptr %cp0, ptr %subj)"
  , "  ret ptr %cp0"
  , "comp.ok:"
  , "  %olen = alloca i64"
  , "  %sl = call i64 @strlen(ptr %subj)"
  , "  %rl = call i64 @strlen(ptr %repl)"
  , "  %isz = add i64 %sl, 256"
  , "  %isz2 = add i64 %isz, %rl"
  , "  store i64 %isz2, ptr %olen"
  , "  %buf = call ptr @malloc(i64 %isz2)"
  , "  %rc = call i32 @pcre2_substitute_8(ptr %re, ptr %subj, i64 -1, i64 0, i32 4096, ptr null, ptr null, ptr %repl, i64 -1, ptr %buf, ptr %olen)"
  , "  %nomem = icmp eq i32 %rc, -48"
  , "  br i1 %nomem, label %retry, label %check"
  , "retry:"
  , "  %need = load i64, ptr %olen"
  , "  %need1 = add i64 %need, 1"
  , "  %buf2 = call ptr @realloc(ptr %buf, i64 %need1)"
  , "  store i64 %need1, ptr %olen"
  , "  %_rc2 = call i32 @pcre2_substitute_8(ptr %re, ptr %subj, i64 -1, i64 0, i32 0, ptr null, ptr null, ptr %repl, i64 -1, ptr %buf2, ptr %olen)"
  , "  ret ptr %buf2"
  , "check:"
  , "  %err = icmp slt i32 %rc, 0"
  , "  br i1 %err, label %fail, label %ok"
  , "fail:"
  , "  call void @free(ptr %buf)"
  , "  %sl1 = call i64 @strlen(ptr %subj)"
  , "  %sl11 = add i64 %sl1, 1"
  , "  %cp1 = call ptr @malloc(i64 %sl11)"
  , "  %_d1 = call ptr @strcpy(ptr %cp1, ptr %subj)"
  , "  ret ptr %cp1"
  , "ok:"
  , "  ret ptr %buf"
  , "}"
  , ""
  -- pll_rx_gsub: replace all
  , "define ptr @pll_rx_gsub(ptr %re, ptr %repl, ptr %subj) {"
  , "entry:"
  , "  %null = icmp eq ptr %re, null"
  , "  br i1 %null, label %copyret, label %comp.ok"
  , "copyret:"
  , "  %sl0 = call i64 @strlen(ptr %subj)"
  , "  %sl01 = add i64 %sl0, 1"
  , "  %cp0 = call ptr @malloc(i64 %sl01)"
  , "  %_d0 = call ptr @strcpy(ptr %cp0, ptr %subj)"
  , "  ret ptr %cp0"
  , "comp.ok:"
  , "  %olen = alloca i64"
  , "  %sl = call i64 @strlen(ptr %subj)"
  , "  %rl = call i64 @strlen(ptr %repl)"
  , "  %sl2 = shl i64 %sl, 1"
  , "  %isz = add i64 %rl, 256"
  , "  %isz2 = add i64 %isz, %sl2"
  , "  store i64 %isz2, ptr %olen"
  , "  %buf = call ptr @malloc(i64 %isz2)"
  , "  %rc = call i32 @pcre2_substitute_8(ptr %re, ptr %subj, i64 -1, i64 0, i32 4352, ptr null, ptr null, ptr %repl, i64 -1, ptr %buf, ptr %olen)"
  , "  %nomem = icmp eq i32 %rc, -48"
  , "  br i1 %nomem, label %retry, label %check"
  , "retry:"
  , "  %need = load i64, ptr %olen"
  , "  %need1 = add i64 %need, 1"
  , "  %buf2 = call ptr @realloc(ptr %buf, i64 %need1)"
  , "  store i64 %need1, ptr %olen"
  , "  %_rc2 = call i32 @pcre2_substitute_8(ptr %re, ptr %subj, i64 -1, i64 0, i32 256, ptr null, ptr null, ptr %repl, i64 -1, ptr %buf2, ptr %olen)"
  , "  ret ptr %buf2"
  , "check:"
  , "  %err = icmp slt i32 %rc, 0"
  , "  br i1 %err, label %fail, label %ok"
  , "fail:"
  , "  call void @free(ptr %buf)"
  , "  %sl1 = call i64 @strlen(ptr %subj)"
  , "  %sl11 = add i64 %sl1, 1"
  , "  %cp1 = call ptr @malloc(i64 %sl11)"
  , "  %_d1 = call ptr @strcpy(ptr %cp1, ptr %subj)"
  , "  ret ptr %cp1"
  , "ok:"
  , "  ret ptr %buf"
  , "}"
  , ""
  -- pll_rx_split: split subject on pattern, return List
  , "define ptr @pll_rx_split(ptr %re, ptr %subj) {"
  , "entry:"
  , "  %null = icmp eq ptr %re, null"
  , "  br i1 %null, label %cfail, label %init"
  , "cfail:"
  , "  %fl = call i64 @strlen(ptr %subj)"
  , "  %fl1 = add i64 %fl, 1"
  , "  %fcp = call ptr @malloc(i64 %fl1)"
  , "  %_fd = call ptr @strcpy(ptr %fcp, ptr %subj)"
  , "  %fnil = call ptr @malloc(i64 8)"
  , "  store i32 0, ptr %fnil"
  , "  %fcons = call ptr @malloc(i64 24)"
  , "  store i32 1, ptr %fcons"
  , "  %fp1 = getelementptr i8, ptr %fcons, i64 8"
  , "  store ptr %fcp, ptr %fp1"
  , "  %fp2 = getelementptr i8, ptr %fcons, i64 16"
  , "  store ptr %fnil, ptr %fp2"
  , "  br label %done"
  , "init:"
  , "  %pa0 = call ptr @malloc(i64 128)"
  , "  %md = call ptr @pcre2_match_data_create_from_pattern_8(ptr %re, ptr null)"
  , "  %slen = call i64 @strlen(ptr %subj)"
  , "  br label %loop"
  , "loop:"
  , "  %cap = phi i64 [ 16, %init ], [ %cap.n, %store ]"
  , "  %cnt = phi i64 [ 0, %init ], [ %cnt.n, %store ]"
  , "  %pa = phi ptr [ %pa0, %init ], [ %pa.n, %store ]"
  , "  %pos = phi i64 [ 0, %init ], [ %pos.n, %store ]"
  , "  %rc = call i32 @pcre2_match_8(ptr %re, ptr %subj, i64 %slen, i64 %pos, i32 0, ptr %md, ptr null)"
  , "  %miss = icmp slt i32 %rc, 0"
  , "  br i1 %miss, label %tail, label %found"
  , "tail:"
  , "  %tl = sub i64 %slen, %pos"
  , "  %tl1 = add i64 %tl, 1"
  , "  %tb = call ptr @malloc(i64 %tl1)"
  , "  %ts = getelementptr i8, ptr %subj, i64 %pos"
  , "  call void @llvm.memcpy.p0.p0.i64(ptr %tb, ptr %ts, i64 %tl, i1 false)"
  , "  %tt = getelementptr i8, ptr %tb, i64 %tl"
  , "  store i8 0, ptr %tt"
  , "  %tfit = icmp ult i64 %cnt, %cap"
  , "  br i1 %tfit, label %tstore, label %tgrow"
  , "tgrow:"
  , "  %tbsz = shl i64 %cap, 4"
  , "  %tpa = call ptr @realloc(ptr %pa, i64 %tbsz)"
  , "  br label %tstore"
  , "tstore:"
  , "  %tpa2 = phi ptr [ %pa, %tail ], [ %tpa, %tgrow ]"
  , "  %tsl = getelementptr ptr, ptr %tpa2, i64 %cnt"
  , "  store ptr %tb, ptr %tsl"
  , "  %tcnt = add i64 %cnt, 1"
  , "  br label %build"
  , "found:"
  , "  %ov = call ptr @pcre2_get_ovector_pointer_8(ptr %md)"
  , "  %ms = load i64, ptr %ov"
  , "  %mep = getelementptr i64, ptr %ov, i32 1"
  , "  %me = load i64, ptr %mep"
  , "  %pl = sub i64 %ms, %pos"
  , "  %pl1 = add i64 %pl, 1"
  , "  %pb = call ptr @malloc(i64 %pl1)"
  , "  %ps = getelementptr i8, ptr %subj, i64 %pos"
  , "  call void @llvm.memcpy.p0.p0.i64(ptr %pb, ptr %ps, i64 %pl, i1 false)"
  , "  %pt = getelementptr i8, ptr %pb, i64 %pl"
  , "  store i8 0, ptr %pt"
  , "  %fit = icmp ult i64 %cnt, %cap"
  , "  br i1 %fit, label %store, label %grow"
  , "grow:"
  , "  %gcap = shl i64 %cap, 1"
  , "  %gbsz = shl i64 %cap, 4"
  , "  %gpa = call ptr @realloc(ptr %pa, i64 %gbsz)"
  , "  br label %store"
  , "store:"
  , "  %pa.n = phi ptr [ %pa, %found ], [ %gpa, %grow ]"
  , "  %cap.n = phi i64 [ %cap, %found ], [ %gcap, %grow ]"
  , "  %sl = getelementptr ptr, ptr %pa.n, i64 %cnt"
  , "  store ptr %pb, ptr %sl"
  , "  %adv = icmp ugt i64 %me, %pos"
  , "  %pp1 = add i64 %pos, 1"
  , "  %pos.n = select i1 %adv, i64 %me, i64 %pp1"
  , "  %cnt.n = add i64 %cnt, 1"
  , "  %pastend = icmp ugt i64 %pos.n, %slen"
  , "  br i1 %pastend, label %build, label %loop"
  , "build:"
  , "  %bpa = phi ptr [ %tpa2, %tstore ], [ %pa.n, %store ]"
  , "  %bcnt = phi i64 [ %tcnt, %tstore ], [ %cnt.n, %store ]"
  , "  call void @pcre2_match_data_free_8(ptr %md)"
  , "  %nil = call ptr @malloc(i64 8)"
  , "  store i32 0, ptr %nil"
  , "  %noparts = icmp eq i64 %bcnt, 0"
  , "  br i1 %noparts, label %cleanup, label %bloop"
  , "bloop:"
  , "  %bi = phi i64 [ %bcnt, %build ], [ %bi1, %bloop ]"
  , "  %bl = phi ptr [ %nil, %build ], [ %bc, %bloop ]"
  , "  %bi1 = sub i64 %bi, 1"
  , "  %bsl = getelementptr ptr, ptr %bpa, i64 %bi1"
  , "  %be = load ptr, ptr %bsl"
  , "  %bc = call ptr @malloc(i64 24)"
  , "  store i32 1, ptr %bc"
  , "  %bp1 = getelementptr i8, ptr %bc, i64 8"
  , "  store ptr %be, ptr %bp1"
  , "  %bp2 = getelementptr i8, ptr %bc, i64 16"
  , "  store ptr %bl, ptr %bp2"
  , "  %bdn = icmp eq i64 %bi1, 0"
  , "  br i1 %bdn, label %cleanup, label %bloop"
  , "cleanup:"
  , "  %result = phi ptr [ %nil, %build ], [ %bc, %bloop ]"
  , "  call void @free(ptr %bpa)"
  , "  br label %done"
  , "done:"
  , "  %ret = phi ptr [ %fcons, %cfail ], [ %result, %cleanup ]"
  , "  ret ptr %ret"
  , "}"
  , ""
  -- pll_rx_captures: capture groups from first match
  , "define ptr @pll_rx_captures(ptr %re, ptr %subj) {"
  , "entry:"
  , "  %null = icmp eq ptr %re, null"
  , "  br i1 %null, label %nil0, label %try"
  , "nil0:"
  , "  %n0 = call ptr @malloc(i64 8)"
  , "  store i32 0, ptr %n0"
  , "  br label %done"
  , "try:"
  , "  %md = call ptr @pcre2_match_data_create_from_pattern_8(ptr %re, ptr null)"
  , "  %rc = call i32 @pcre2_match_8(ptr %re, ptr %subj, i64 -1, i64 0, i32 0, ptr %md, ptr null)"
  , "  %miss = icmp slt i32 %rc, 0"
  , "  br i1 %miss, label %nil1, label %matched"
  , "nil1:"
  , "  call void @pcre2_match_data_free_8(ptr %md)"
  , "  %n1 = call ptr @malloc(i64 8)"
  , "  store i32 0, ptr %n1"
  , "  br label %done"
  , "matched:"
  , "  %ov = call ptr @pcre2_get_ovector_pointer_8(ptr %md)"
  , "  %ng = call i32 @pcre2_get_ovector_count_8(ptr %md)"
  , "  %nil.m = call ptr @malloc(i64 8)"
  , "  store i32 0, ptr %nil.m"
  , "  %last = sub i32 %ng, 1"
  , "  %nogrp = icmp eq i32 %last, 0"
  , "  br i1 %nogrp, label %free, label %linit"
  , "linit:"
  , "  %ii = zext i32 %last to i64"
  , "  br label %cloop"
  , "cloop:"
  , "  %ci = phi i64 [ %ii, %linit ], [ %ci1, %cmerge ]"
  , "  %cl = phi ptr [ %nil.m, %linit ], [ %cc, %cmerge ]"
  , "  %ci32 = trunc i64 %ci to i32"
  , "  %idx = shl i32 %ci32, 1"
  , "  %idxl = zext i32 %idx to i64"
  , "  %sp = getelementptr i64, ptr %ov, i64 %idxl"
  , "  %sv = load i64, ptr %sp"
  , "  %unset = icmp eq i64 %sv, -1"
  , "  br i1 %unset, label %cempty, label %cextract"
  , "cempty:"
  , "  %eb = call ptr @malloc(i64 1)"
  , "  store i8 0, ptr %eb"
  , "  br label %cmerge"
  , "cextract:"
  , "  %idx1 = or i32 %idx, 1"
  , "  %idx1l = zext i32 %idx1 to i64"
  , "  %ep = getelementptr i64, ptr %ov, i64 %idx1l"
  , "  %ev = load i64, ptr %ep"
  , "  %cl2 = sub i64 %ev, %sv"
  , "  %cl21 = add i64 %cl2, 1"
  , "  %cb = call ptr @malloc(i64 %cl21)"
  , "  %cs = getelementptr i8, ptr %subj, i64 %sv"
  , "  call void @llvm.memcpy.p0.p0.i64(ptr %cb, ptr %cs, i64 %cl2, i1 false)"
  , "  %ct = getelementptr i8, ptr %cb, i64 %cl2"
  , "  store i8 0, ptr %ct"
  , "  br label %cmerge"
  , "cmerge:"
  , "  %ce = phi ptr [ %eb, %cempty ], [ %cb, %cextract ]"
  , "  %cc = call ptr @malloc(i64 24)"
  , "  store i32 1, ptr %cc"
  , "  %cp1 = getelementptr i8, ptr %cc, i64 8"
  , "  store ptr %ce, ptr %cp1"
  , "  %cp2 = getelementptr i8, ptr %cc, i64 16"
  , "  store ptr %cl, ptr %cp2"
  , "  %ci1 = sub i64 %ci, 1"
  , "  %ci1m = and i64 %ci1, 4294967295"
  , "  %cdn = icmp eq i64 %ci1m, 0"
  , "  br i1 %cdn, label %free, label %cloop"
  , "free:"
  , "  %fl2 = phi ptr [ %nil.m, %matched ], [ %cc, %cmerge ]"
  , "  call void @pcre2_match_data_free_8(ptr %md)"
  , "  br label %done"
  , "done:"
  , "  %ret = phi ptr [ %n0, %nil0 ], [ %n1, %nil1 ], [ %fl2, %free ]"
  , "  ret ptr %ret"
  , "}"
  ]
