{-# LANGUAGE OverloadedStrings #-}

-- MODULE

module Pllisp.Codegen (codegen) where

import qualified Pllisp.BuiltIn as BuiltIn
import qualified Pllisp.CST as CST
import qualified Pllisp.LambdaLift as LL
import qualified Pllisp.Type as Ty

import Control.Monad (forM_, void)
import Control.Monad.State.Strict
import qualified Data.Map.Strict as M
import qualified Data.Set as S
import qualified Data.Text as T

-- TYPES

data CtorInfo = CtorInfo
  { ciTag  :: !Int
  , ciArgs :: [Ty.Type]
  } deriving (Show)

data CgState = CgState
  { csFresh   :: !Int
  , csStrLits :: [(T.Text, T.Text)]       -- (global name, value), reverse order
  , csBlock   :: T.Text                    -- current basic block label
  , csVars    :: M.Map CST.Symbol T.Text   -- pllisp name → LLVM operand
  , csCtors   :: M.Map CST.Symbol CtorInfo -- constructor info from TYPE decls
  , csDefs    :: M.Map CST.Symbol LL.LLDef -- lifted function defs
  , csInstrs  :: [T.Text]                  -- instructions, reverse order
  }

type CgM = State CgState

-- Every struct field is 8-byte aligned for uniform layout
slotSize :: Int
slotSize = 8

-- ENTRY POINT

codegen :: LL.LLProgram -> T.Text
codegen prog = evalState go initState
  where
    ctors    = collectCtors (LL.llExprs prog)
    defMap   = M.fromList [(LL.defName d, d) | d <- LL.llDefs prog]
    initState = CgState 0 [] "entry" M.empty ctors defMap []

    go :: CgM T.Text
    go = do
      defTexts <- mapM genDef (LL.llDefs prog)
      mainText <- genMain (LL.llExprs prog)
      strLits  <- gets (reverse . csStrLits)
      let strDecls = map genStrDecl strLits
      pure $ T.unlines $
        [ moduleHeader, "" ]
        ++ [ externDecls ]
        ++ [ fmtConstants ]
        ++ strDecls
        ++ [ "" ]
        ++ defTexts
        ++ [ mainText ]

-- MODULE-LEVEL DECLARATIONS

moduleHeader :: T.Text
moduleHeader = "; Generated by pllisp"

externDecls :: T.Text
externDecls = T.unlines
  [ "declare ptr @malloc(i64)"
  , "declare void @free(ptr)"
  , "declare i32 @puts(ptr)"
  , "declare i64 @strlen(ptr)"
  , "declare i32 @strcmp(ptr, ptr)"
  , "declare ptr @strcpy(ptr, ptr)"
  , "declare ptr @strcat(ptr, ptr)"
  , "declare i32 @snprintf(ptr, i64, ptr, ...)"
  , "declare ptr @fgets(ptr, i32, ptr)"
  , "@stdin = external global ptr"
  ]

fmtConstants :: T.Text
fmtConstants = T.unlines
  [ "@fmt.int = private unnamed_addr constant [4 x i8] c\"%ld\\00\""
  , "@fmt.flt = private unnamed_addr constant [3 x i8] c\"%g\\00\""
  ]

genStrDecl :: (T.Text, T.Text) -> T.Text
genStrDecl (name, value) =
  let escaped = escapeForLLVM value
      len = T.length value + 1  -- +1 for null terminator
  in "@" <> name <> " = private unnamed_addr constant ["
     <> tshow len <> " x i8] c\"" <> escaped <> "\\00\""

escapeForLLVM :: T.Text -> T.Text
escapeForLLVM = T.concatMap escChar
  where
    escChar '\\' = "\\\\"
    escChar '"'  = "\\22"
    escChar '\n' = "\\0A"
    escChar '\t' = "\\09"
    escChar c    = T.singleton c

-- TYPE INFO COLLECTION

collectCtors :: [LL.LLExpr] -> M.Map CST.Symbol CtorInfo
collectCtors = foldl' go M.empty
  where
    go acc (Ty.Typed _ (LL.LLType _ _ dataCons)) =
      foldl' addCtor acc (zip [0..] dataCons)
    go acc _ = acc
    addCtor acc (tag, CST.DataCon name fields) =
      M.insert name (CtorInfo tag fields) acc

-- LLVM TYPE MAPPING

llvmType :: Ty.Type -> T.Text
llvmType Ty.TyInt       = "i64"
llvmType Ty.TyFlt       = "double"
llvmType Ty.TyStr       = "ptr"
llvmType Ty.TyBool      = "i1"
llvmType Ty.TyUnit      = "i8"
llvmType (Ty.TyFun _ _) = "ptr"
llvmType (Ty.TyCon _ _) = "ptr"
llvmType (Ty.TyVar _)   = "ptr"

-- STATE HELPERS

fresh :: CgM T.Text
fresh = do
  n <- gets csFresh
  modify' (\s -> s { csFresh = n + 1 })
  pure ("%t" <> tshow n)

freshLabel :: T.Text -> CgM T.Text
freshLabel prefix = do
  n <- gets csFresh
  modify' (\s -> s { csFresh = n + 1 })
  pure (prefix <> "." <> tshow n)

emit :: T.Text -> CgM ()
emit line = modify' (\s -> s { csInstrs = ("  " <> line) : csInstrs s })

emitLabel :: T.Text -> CgM ()
emitLabel lbl =
  modify' (\s -> s { csInstrs = (lbl <> ":") : csInstrs s, csBlock = lbl })

addStrLit :: T.Text -> CgM T.Text
addStrLit value = do
  lits <- gets csStrLits
  case lookup value [(v, n) | (n, v) <- lits] of
    Just name -> pure ("@" <> name)
    Nothing -> do
      let name = "str." <> tshow (length lits)
      modify' (\s -> s { csStrLits = (name, value) : csStrLits s })
      pure ("@" <> name)

bindVar :: CST.Symbol -> T.Text -> CgM ()
bindVar name op = modify' (\s -> s { csVars = M.insert name op (csVars s) })

lookupVar :: CST.Symbol -> CgM T.Text
lookupVar name = do
  vars <- gets csVars
  case M.lookup name vars of
    Just op -> pure op
    Nothing -> do
      ctors <- gets csCtors
      case M.lookup name ctors of
        Just ci | null (ciArgs ci) -> genCtorAlloc ci []
        _ -> error ("Codegen: unbound variable: " <> T.unpack name)

tshow :: Show a => a -> T.Text
tshow = T.pack . show

sanitize :: T.Text -> T.Text
sanitize = T.concatMap (\c -> if c == '-' then "_" else T.singleton c)

-- FUNCTION GENERATION

genDef :: LL.LLDef -> CgM T.Text
genDef def = do
  savedVars   <- gets csVars
  savedInstrs <- gets csInstrs
  savedBlock  <- gets csBlock
  modify' (\s -> s { csVars = M.empty, csInstrs = [], csBlock = "entry" })

  -- Bind regular params
  forM_ (LL.defParams def) $ \(pname, _) ->
    bindVar pname ("%" <> sanitize pname)

  -- Unpack env from closure pointer
  forM_ (zip [0..] (LL.defEnv def)) $ \(i, (ename, ety)) -> do
    let offset = slotSize * (i + 1)  -- skip fnptr at offset 0
    ptr <- fresh
    val <- fresh
    emit (ptr <> " = getelementptr i8, ptr %__closure, i64 " <> tshow offset)
    emit (val <> " = load " <> llvmType ety <> ", ptr " <> ptr)
    bindVar ename val

  -- Generate body and return
  result <- genExpr (LL.defBody def)
  let retTy = LL.defRetTy def
  emit ("ret " <> llvmType retTy <> " " <> result)

  instrs <- gets (reverse . csInstrs)
  modify' (\s -> s { csVars = savedVars, csInstrs = savedInstrs, csBlock = savedBlock })

  let paramList = "ptr %__closure" <>
        T.concat [", " <> llvmType pty <> " %" <> sanitize pname
                 | (pname, pty) <- LL.defParams def]

  pure $ T.unlines $
    [ "define " <> llvmType retTy <> " @" <> sanitize (LL.defName def)
      <> "(" <> paramList <> ") {"
    , "entry:" ]
    ++ instrs
    ++ [ "}", "" ]

genMain :: [LL.LLExpr] -> CgM T.Text
genMain exprs = do
  savedVars   <- gets csVars
  savedInstrs <- gets csInstrs
  savedBlock  <- gets csBlock
  modify' (\s -> s { csVars = M.empty, csInstrs = [], csBlock = "entry" })

  mapM_ genTopExpr exprs
  emit "ret i32 0"

  instrs <- gets (reverse . csInstrs)
  modify' (\s -> s { csVars = savedVars, csInstrs = savedInstrs, csBlock = savedBlock })

  pure $ T.unlines $
    [ "define i32 @main() {"
    , "entry:" ]
    ++ instrs
    ++ [ "}" ]

genTopExpr :: LL.LLExpr -> CgM ()
genTopExpr (Ty.Typed _ (LL.LLType {})) = pure ()
genTopExpr expr = void (genExpr expr)

-- EXPRESSION GENERATION

genExpr :: LL.LLExpr -> CgM T.Text
genExpr (Ty.Typed t expr) = case expr of
  LL.LLLit lit   -> genLit lit
  LL.LLBool b    -> pure (if b then "1" else "0")
  LL.LLUnit      -> pure "0"
  LL.LLVar name _ -> lookupVar name

  LL.LLLet binds body -> do
    savedVars <- gets csVars
    forM_ binds $ \(name, _, rhs) -> do
      op <- genExpr rhs
      bindVar name op
    result <- genExpr body
    modify' (\s -> s { csVars = savedVars })
    pure result

  LL.LLIf cond thenE elseE -> genIf t cond thenE elseE
  LL.LLApp func args       -> genApp t func args
  LL.LLMkClosure name envs -> genMkClosure name envs
  LL.LLCase scr arms       -> genCase t scr arms
  LL.LLType {}             -> pure "0"

genLit :: CST.Literal -> CgM T.Text
genLit (CST.LitInt n) = pure (tshow n)
genLit (CST.LitFlt f) = pure (T.pack (showFlt f))
genLit (CST.LitStr s) = addStrLit s

showFlt :: Double -> String
showFlt f =
  let s = show f
  in if '.' `elem` s || 'e' `elem` s || 'E' `elem` s then s else s ++ ".0"

-- IF/THEN/ELSE

genIf :: Ty.Type -> LL.LLExpr -> LL.LLExpr -> LL.LLExpr -> CgM T.Text
genIf resTy cond thenE elseE = do
  condOp   <- genExpr cond
  thenLbl  <- freshLabel "then"
  elseLbl  <- freshLabel "else"
  mergeLbl <- freshLabel "merge"

  emit ("br i1 " <> condOp <> ", label %" <> thenLbl <> ", label %" <> elseLbl)

  emitLabel thenLbl
  thenOp   <- genExpr thenE
  thenExit <- gets csBlock
  emit ("br label %" <> mergeLbl)

  emitLabel elseLbl
  elseOp   <- genExpr elseE
  elseExit <- gets csBlock
  emit ("br label %" <> mergeLbl)

  emitLabel mergeLbl
  result <- fresh
  emit (result <> " = phi " <> llvmType resTy
    <> " [" <> thenOp <> ", %" <> thenExit <> "]"
    <> ", [" <> elseOp <> ", %" <> elseExit <> "]")
  pure result

-- APPLICATION

genApp :: Ty.Type -> LL.LLExpr -> [LL.LLExpr] -> CgM T.Text
genApp resTy func args = do
  argResults <- mapM (\a -> do op <- genExpr a; pure (Ty.ty a, op)) args
  ctors <- gets csCtors

  case Ty.val func of
    LL.LLVar name _ | S.member name BuiltIn.builtInNames ->
      genBuiltIn name argResults resTy
    LL.LLVar name _ | M.member name ctors ->
      genCtorAlloc (ctors M.! name) argResults
    _ -> do
      closureOp <- genExpr func
      genClosureCall closureOp argResults resTy

-- CLOSURE OPERATIONS

genMkClosure :: CST.Symbol -> [LL.LLExpr] -> CgM T.Text
genMkClosure name envArgs = do
  let totalSize = slotSize * (1 + length envArgs)
  closure <- fresh
  emit (closure <> " = call ptr @malloc(i64 " <> tshow totalSize <> ")")

  -- Store function pointer at offset 0
  emit ("store ptr @" <> sanitize name <> ", ptr " <> closure)

  -- Store env values at subsequent offsets
  forM_ (zip [1..] envArgs) $ \(i, envExpr) -> do
    envOp <- genExpr envExpr
    ptr <- fresh
    emit (ptr <> " = getelementptr i8, ptr " <> closure
      <> ", i64 " <> tshow (slotSize * (i :: Int)))
    emit ("store " <> llvmType (Ty.ty envExpr) <> " " <> envOp <> ", ptr " <> ptr)

  pure closure

genClosureCall :: T.Text -> [(Ty.Type, T.Text)] -> Ty.Type -> CgM T.Text
genClosureCall closureOp argResults resTy = do
  fnptr <- fresh
  emit (fnptr <> " = load ptr, ptr " <> closureOp)

  let argList = "ptr " <> closureOp <>
        T.concat [", " <> llvmType t <> " " <> op | (t, op) <- argResults]

  result <- fresh
  emit (result <> " = call " <> llvmType resTy <> " "
    <> fnptr <> "(" <> argList <> ")")
  pure result

-- CONSTRUCTOR OPERATIONS

genCtorAlloc :: CtorInfo -> [(Ty.Type, T.Text)] -> CgM T.Text
genCtorAlloc ci args = do
  let totalSize = slotSize * (1 + length args)
  obj <- fresh
  emit (obj <> " = call ptr @malloc(i64 " <> tshow totalSize <> ")")

  -- Store tag at offset 0
  emit ("store i32 " <> tshow (ciTag ci) <> ", ptr " <> obj)

  -- Store fields at subsequent offsets
  forM_ (zip [1..] args) $ \(i, (argTy, argOp)) -> do
    ptr <- fresh
    emit (ptr <> " = getelementptr i8, ptr " <> obj
      <> ", i64 " <> tshow (slotSize * (i :: Int)))
    emit ("store " <> llvmType argTy <> " " <> argOp <> ", ptr " <> ptr)

  pure obj

-- CASE EXPRESSIONS

genCase :: Ty.Type -> LL.LLExpr -> [(LL.LLPattern, LL.LLExpr)] -> CgM T.Text
genCase resTy scr arms = do
  scrOp    <- genExpr scr
  mergeLbl <- freshLabel "case.merge"
  phiPairs <- genArms scrOp arms mergeLbl

  emitLabel mergeLbl
  if null phiPairs
    then do
      emit "unreachable"
      pure "0"
    else do
      result <- fresh
      let phiArgs = T.intercalate ", "
            ["[" <> op <> ", %" <> lbl <> "]" | (op, lbl) <- phiPairs]
      emit (result <> " = phi " <> llvmType resTy <> " " <> phiArgs)
      pure result

genArms :: T.Text -> [(LL.LLPattern, LL.LLExpr)] -> T.Text -> CgM [(T.Text, T.Text)]
genArms _ [] _ = do
  emit "unreachable"
  pure []
genArms scrOp ((pat, body):rest) mergeLbl = case pat of
  LL.LLPatWild _ -> genCatchAllArm scrOp pat body mergeLbl
  LL.LLPatVar {} -> genCatchAllArm scrOp pat body mergeLbl
  _ -> do
    matchLbl <- freshLabel "case.match"
    nextLbl  <- freshLabel "case.next"
    genPatTest scrOp pat matchLbl nextLbl

    emitLabel matchLbl
    savedVars <- gets csVars
    bindPatVars scrOp pat
    bodyOp   <- genExpr body
    bodyExit <- gets csBlock
    emit ("br label %" <> mergeLbl)
    modify' (\s -> s { csVars = savedVars })

    emitLabel nextLbl
    restPairs <- genArms scrOp rest mergeLbl
    pure ((bodyOp, bodyExit) : restPairs)

genCatchAllArm :: T.Text -> LL.LLPattern -> LL.LLExpr -> T.Text -> CgM [(T.Text, T.Text)]
genCatchAllArm scrOp pat body mergeLbl = do
  savedVars <- gets csVars
  case pat of
    LL.LLPatVar name _ -> bindVar name scrOp
    _                  -> pure ()
  bodyOp   <- genExpr body
  bodyExit <- gets csBlock
  emit ("br label %" <> mergeLbl)
  modify' (\s -> s { csVars = savedVars })
  pure [(bodyOp, bodyExit)]

genPatTest :: T.Text -> LL.LLPattern -> T.Text -> T.Text -> CgM ()
genPatTest scrOp pat matchLbl nextLbl = case pat of
  LL.LLPatBool b -> do
    cmp <- fresh
    emit (cmp <> " = icmp eq i1 " <> scrOp <> ", " <> if b then "1" else "0")
    emit ("br i1 " <> cmp <> ", label %" <> matchLbl <> ", label %" <> nextLbl)

  LL.LLPatLit (CST.LitInt n) -> do
    cmp <- fresh
    emit (cmp <> " = icmp eq i64 " <> scrOp <> ", " <> tshow n)
    emit ("br i1 " <> cmp <> ", label %" <> matchLbl <> ", label %" <> nextLbl)

  LL.LLPatLit (CST.LitFlt f) -> do
    cmp <- fresh
    emit (cmp <> " = fcmp oeq double " <> scrOp <> ", " <> T.pack (showFlt f))
    emit ("br i1 " <> cmp <> ", label %" <> matchLbl <> ", label %" <> nextLbl)

  LL.LLPatLit (CST.LitStr s) -> do
    strPtr <- addStrLit s
    cmpR   <- fresh
    emit (cmpR <> " = call i32 @strcmp(ptr " <> scrOp <> ", ptr " <> strPtr <> ")")
    cmp <- fresh
    emit (cmp <> " = icmp eq i32 " <> cmpR <> ", 0")
    emit ("br i1 " <> cmp <> ", label %" <> matchLbl <> ", label %" <> nextLbl)

  LL.LLPatCon ctorName _ _ -> do
    ctors <- gets csCtors
    let ci = ctors M.! ctorName
    tagR <- fresh
    emit (tagR <> " = load i32, ptr " <> scrOp)
    cmp <- fresh
    emit (cmp <> " = icmp eq i32 " <> tagR <> ", " <> tshow (ciTag ci))
    emit ("br i1 " <> cmp <> ", label %" <> matchLbl <> ", label %" <> nextLbl)

  -- Wildcard/var handled in genArms before reaching here
  _ -> emit ("br label %" <> matchLbl)

bindPatVars :: T.Text -> LL.LLPattern -> CgM ()
bindPatVars scrOp pat = case pat of
  LL.LLPatCon _ _ subPats ->
    forM_ (zip [1..] subPats) $ \(i, subPat) -> do
      let offset = slotSize * (i :: Int)
      fieldPtr <- fresh
      emit (fieldPtr <> " = getelementptr i8, ptr " <> scrOp
        <> ", i64 " <> tshow offset)
      let fty = patType subPat
      fieldVal <- fresh
      emit (fieldVal <> " = load " <> llvmType fty <> ", ptr " <> fieldPtr)
      case subPat of
        LL.LLPatVar name _ -> bindVar name fieldVal
        _                  -> pure ()
  LL.LLPatVar name _ -> bindVar name scrOp
  _ -> pure ()

patType :: LL.LLPattern -> Ty.Type
patType (LL.LLPatLit (CST.LitInt _)) = Ty.TyInt
patType (LL.LLPatLit (CST.LitFlt _)) = Ty.TyFlt
patType (LL.LLPatLit (CST.LitStr _)) = Ty.TyStr
patType (LL.LLPatBool _)             = Ty.TyBool
patType (LL.LLPatVar _ ty)           = ty
patType (LL.LLPatWild ty)            = ty
patType (LL.LLPatCon _ ty _)         = ty

-- BUILT-IN FUNCTIONS

genBuiltIn :: CST.Symbol -> [(Ty.Type, T.Text)] -> Ty.Type -> CgM T.Text
genBuiltIn name args _resTy = case name of
  -- Int arithmetic
  "ADD" -> intBinOp "add" args
  "SUB" -> intBinOp "sub" args
  "MUL" -> intBinOp "mul" args
  "DIV" -> intBinOp "sdiv" args
  "MOD" -> intBinOp "srem" args
  "NEG" -> do
    let (_, op) = head args
    r <- fresh
    emit (r <> " = sub i64 0, " <> op)
    pure r

  -- Float arithmetic
  "ADDF" -> fltBinOp "fadd" args
  "SUBF" -> fltBinOp "fsub" args
  "MULF" -> fltBinOp "fmul" args
  "DIVF" -> fltBinOp "fdiv" args
  "NEGF" -> do
    let (_, op) = head args
    r <- fresh
    emit (r <> " = fsub double 0.0, " <> op)
    pure r

  -- Int comparison
  "EQ" -> intCmp "eq" args
  "LT" -> intCmp "slt" args
  "GT" -> intCmp "sgt" args
  "LE" -> intCmp "sle" args
  "GE" -> intCmp "sge" args

  -- Float comparison
  "EQF" -> fltCmp "oeq" args
  "LTF" -> fltCmp "olt" args
  "GTF" -> fltCmp "ogt" args
  "LEF" -> fltCmp "ole" args
  "GEF" -> fltCmp "oge" args

  -- Boolean
  "AND" -> do
    let [(_, a), (_, b)] = args
    r <- fresh
    emit (r <> " = and i1 " <> a <> ", " <> b)
    pure r
  "OR" -> do
    let [(_, a), (_, b)] = args
    r <- fresh
    emit (r <> " = or i1 " <> a <> ", " <> b)
    pure r
  "NOT" -> do
    let [(_, op)] = args
    r <- fresh
    emit (r <> " = xor i1 " <> op <> ", 1")
    pure r

  -- String comparison
  "EQS" -> do
    let [(_, s1), (_, s2)] = args
    cmpR <- fresh
    emit (cmpR <> " = call i32 @strcmp(ptr " <> s1 <> ", ptr " <> s2 <> ")")
    r <- fresh
    emit (r <> " = icmp eq i32 " <> cmpR <> ", 0")
    pure r

  -- String operations
  "CONCAT" -> do
    let [(_, s1), (_, s2)] = args
    len1 <- fresh
    emit (len1 <> " = call i64 @strlen(ptr " <> s1 <> ")")
    len2 <- fresh
    emit (len2 <> " = call i64 @strlen(ptr " <> s2 <> ")")
    total <- fresh
    emit (total <> " = add i64 " <> len1 <> ", " <> len2)
    total1 <- fresh
    emit (total1 <> " = add i64 " <> total <> ", 1")
    buf <- fresh
    emit (buf <> " = call ptr @malloc(i64 " <> total1 <> ")")
    d1 <- fresh
    emit (d1 <> " = call ptr @strcpy(ptr " <> buf <> ", ptr " <> s1 <> ")")
    d2 <- fresh
    emit (d2 <> " = call ptr @strcat(ptr " <> buf <> ", ptr " <> s2 <> ")")
    pure buf

  "STRLEN" -> do
    let [(_, s)] = args
    r <- fresh
    emit (r <> " = call i64 @strlen(ptr " <> s <> ")")
    pure r

  -- IO
  "PRINT" -> do
    let [(_, s)] = args
    d <- fresh
    emit (d <> " = call i32 @puts(ptr " <> s <> ")")
    pure "0"

  "READ-LINE" -> do
    buf <- fresh
    emit (buf <> " = call ptr @malloc(i64 1024)")
    stdinVal <- fresh
    emit (stdinVal <> " = load ptr, ptr @stdin")
    d <- fresh
    emit (d <> " = call ptr @fgets(ptr " <> buf <> ", i32 1024, ptr " <> stdinVal <> ")")
    -- Strip trailing newline
    len <- fresh
    emit (len <> " = call i64 @strlen(ptr " <> buf <> ")")
    lenM1 <- fresh
    emit (lenM1 <> " = sub i64 " <> len <> ", 1")
    lastPtr <- fresh
    emit (lastPtr <> " = getelementptr i8, ptr " <> buf <> ", i64 " <> lenM1)
    emit ("store i8 0, ptr " <> lastPtr)
    pure buf

  -- Conversion
  "INT-TO-FLT" -> do
    let [(_, op)] = args
    r <- fresh
    emit (r <> " = sitofp i64 " <> op <> " to double")
    pure r

  "FLT-TO-INT" -> do
    let [(_, op)] = args
    r <- fresh
    emit (r <> " = fptosi double " <> op <> " to i64")
    pure r

  "INT-TO-STR" -> do
    let [(_, op)] = args
    buf <- fresh
    emit (buf <> " = call ptr @malloc(i64 21)")
    d <- fresh
    emit (d <> " = call i32 (ptr, i64, ptr, ...) @snprintf(ptr " <> buf
      <> ", i64 21, ptr @fmt.int, i64 " <> op <> ")")
    pure buf

  "FLT-TO-STR" -> do
    let [(_, op)] = args
    buf <- fresh
    emit (buf <> " = call ptr @malloc(i64 32)")
    d <- fresh
    emit (d <> " = call i32 (ptr, i64, ptr, ...) @snprintf(ptr " <> buf
      <> ", i64 32, ptr @fmt.flt, double " <> op <> ")")
    pure buf

  _ -> error ("Codegen: unknown built-in: " <> T.unpack name)

-- Helpers for binary ops

intBinOp :: T.Text -> [(Ty.Type, T.Text)] -> CgM T.Text
intBinOp op [(_, a), (_, b)] = do
  r <- fresh; emit (r <> " = " <> op <> " i64 " <> a <> ", " <> b); pure r
intBinOp _ _ = error "intBinOp: expected 2 args"

fltBinOp :: T.Text -> [(Ty.Type, T.Text)] -> CgM T.Text
fltBinOp op [(_, a), (_, b)] = do
  r <- fresh; emit (r <> " = " <> op <> " double " <> a <> ", " <> b); pure r
fltBinOp _ _ = error "fltBinOp: expected 2 args"

intCmp :: T.Text -> [(Ty.Type, T.Text)] -> CgM T.Text
intCmp p [(_, a), (_, b)] = do
  r <- fresh; emit (r <> " = icmp " <> p <> " i64 " <> a <> ", " <> b); pure r
intCmp _ _ = error "intCmp: expected 2 args"

fltCmp :: T.Text -> [(Ty.Type, T.Text)] -> CgM T.Text
fltCmp p [(_, a), (_, b)] = do
  r <- fresh; emit (r <> " = fcmp " <> p <> " double " <> a <> ", " <> b); pure r
fltCmp _ _ = error "fltCmp: expected 2 args"
