{-# LANGUAGE OverloadedStrings #-}

module Pllisp.Type where

import qualified Data.Map.Strict as M
import qualified Data.Text as T

-- CORE

type Symbol = T.Text

data Typed a = Typed
  { ty  :: Type
  , val :: a
  } deriving (Eq, Show)

data Type
  = TyInt
  | TyFlt
  | TyStr
  | TyBool
  | TyUnit
  | TyRx
  | TyUSym
  | TySyntax
  | TyFun [Type] Type
  | TyCon Symbol [Type]  -- user-defined: TyCon "Maybe" [TyInt]
  | TyApp Type Type      -- HKT application: TyApp (TyVar 0) TyInt
  | TyVar Integer
  deriving (Eq, Show)

-- C types for FFI declarations. These represent the actual C ABI types
-- (which may differ from pllisp's native LLVM types).
data CType
  = CI8 | CI16 | CI32 | CI64
  | CU8 | CU16 | CU32 | CU64
  | CF32 | CF64
  | CPtr
  | CVoid
  | CArr !Int CType       -- fixed-size inline array: CArr count elemType
  | CStruct T.Text        -- reference to a named struct (for nested structs)
  deriving (Eq, Show)

-- The pllisp type that a CType maps to for the purposes of the type checker.
cTypeToPllisp :: CType -> Type
cTypeToPllisp CI8  = TyInt
cTypeToPllisp CI16 = TyInt
cTypeToPllisp CI32 = TyInt
cTypeToPllisp CI64 = TyInt
cTypeToPllisp CU8  = TyInt
cTypeToPllisp CU16 = TyInt
cTypeToPllisp CU32 = TyInt
cTypeToPllisp CU64 = TyInt
cTypeToPllisp CF32 = TyFlt
cTypeToPllisp CF64 = TyFlt
cTypeToPllisp CPtr = TyStr
cTypeToPllisp CVoid = TyUnit
cTypeToPllisp (CArr _ _) = TyStr  -- array fields accessed as pointers
cTypeToPllisp (CStruct name) = TyCon name []  -- nested struct type

-- Numeric tag for CType, used by the libffi bridge.
-- Must match the tag_to_ffi_type array in ffiBridgeC.
cTypeTag :: CType -> Int
cTypeTag CI8  = 0
cTypeTag CI16 = 1
cTypeTag CI32 = 2
cTypeTag CI64 = 3
cTypeTag CU8  = 4
cTypeTag CU16 = 5
cTypeTag CU32 = 6
cTypeTag CU64 = 7
cTypeTag CF32 = 8
cTypeTag CF64 = 9
cTypeTag CPtr = 10
cTypeTag CVoid = 11
cTypeTag (CArr _ _) = 10  -- treated as pointer
cTypeTag (CStruct _) = 10  -- treated as pointer

-- The C source for the libffi bridge runtime.
-- Compiled alongside the generated LLVM IR.
ffiBridgeC :: T.Text
ffiBridgeC = T.unlines
  [ "#include <ffi.h>"
  , "#include <stdint.h>"
  , "#include <stdio.h>"
  , "#include <stdlib.h>"
  , "#include <string.h>"
  , "#include <errno.h>"
  , "#include <dirent.h>"
  , "#include <sys/stat.h>"
  , "#include <unistd.h>"
  , "#include <gc.h>"
  , ""
  , "static ffi_type* tag_to_ffi_type(int tag) {"
  , "    static ffi_type* types[] = {"
  , "        &ffi_type_sint8,   /* 0  CI8  */"
  , "        &ffi_type_sint16,  /* 1  CI16 */"
  , "        &ffi_type_sint32,  /* 2  CI32 */"
  , "        &ffi_type_sint64,  /* 3  CI64 */"
  , "        &ffi_type_uint8,   /* 4  CU8  */"
  , "        &ffi_type_uint16,  /* 5  CU16 */"
  , "        &ffi_type_uint32,  /* 6  CU32 */"
  , "        &ffi_type_uint64,  /* 7  CU64 */"
  , "        &ffi_type_float,   /* 8  CF32 */"
  , "        &ffi_type_double,  /* 9  CF64 */"
  , "        &ffi_type_pointer, /* 10 CPtr */"
  , "        &ffi_type_void,    /* 11 CVoid */"
  , "    };"
  , "    return types[tag];"
  , "}"
  , ""
  , "static ffi_type* pll_inner_ffi_type(int tag) {"
  , "    switch (tag) {"
  , "        case 8:  return &ffi_type_double;  /* CF32 -> double in pllisp */"
  , "        case 9:  return &ffi_type_double;  /* CF64 -> double in pllisp */"
  , "        case 10: return &ffi_type_pointer; /* CPtr -> ptr in pllisp */"
  , "        case 11: return &ffi_type_sint8;   /* CVoid -> unit/i8 in pllisp */"
  , "        default: return &ffi_type_sint64;  /* integer widths -> i64 in pllisp */"
  , "    }"
  , "}"
  , ""
  , "void pll_ffi_call(void *fn, int nargs, int *arg_types,"
  , "                  int ret_type, void **arg_vals, void *ret_val) {"
  , "    ffi_cif cif;"
  , "    ffi_type *atypes[nargs > 0 ? nargs : 1];"
  , "    for (int i = 0; i < nargs; i++)"
  , "        atypes[i] = tag_to_ffi_type(arg_types[i]);"
  , "    ffi_type *rtype = tag_to_ffi_type(ret_type);"
  , "    ffi_prep_cif(&cif, FFI_DEFAULT_ABI, (unsigned)nargs,"
  , "                 rtype, nargs > 0 ? atypes : NULL);"
  , "    ffi_call(&cif, FFI_FN(fn), ret_val, nargs > 0 ? arg_vals : NULL);"
  , "}"
  , ""
  , "void pll_ffi_call_var(void *fn, int nfixed, int nargs, int *arg_types,"
  , "                      int ret_type, void **arg_vals, void *ret_val) {"
  , "    ffi_cif cif;"
  , "    ffi_type *atypes[nargs > 0 ? nargs : 1];"
  , "    for (int i = 0; i < nargs; i++)"
  , "        atypes[i] = tag_to_ffi_type(arg_types[i]);"
  , "    ffi_type *rtype = tag_to_ffi_type(ret_type);"
  , "    ffi_prep_cif_var(&cif, FFI_DEFAULT_ABI, (unsigned)nfixed, (unsigned)nargs,"
  , "                     rtype, nargs > 0 ? atypes : NULL);"
  , "    ffi_call(&cif, FFI_FN(fn), ret_val, nargs > 0 ? arg_vals : NULL);"
  , "}"
  , ""
  , "/* Callback support: wraps a pllisp closure into a C function pointer. */"
  , "/* The closure layout is: [fnptr, env0, env1, ...] */"
  , "/* The generated C callback calls fnptr(closure_ptr, c_arg0, c_arg1, ...) */"
  , ""
  , "typedef struct {"
  , "    void *closure;       /* pllisp closure pointer */"
  , "    int nargs;           /* number of C args */"
  , "    int *arg_types;      /* CType tags for C args */"
  , "    int ret_type;        /* CType tag for C return */"
  , "    ffi_cif inner_cif;   /* CIF for calling pllisp function */"
  , "} pll_cb_data;"
  , ""
  , "typedef union {"
  , "    int64_t i64;"
  , "    double f64;"
  , "    void *ptr;"
  , "    int8_t i8;"
  , "} pll_cb_value;"
  , ""
  , "static void pll_cb_handler(ffi_cif *cif, void *ret, void **args, void *user_data) {"
  , "    pll_cb_data *data = (pll_cb_data *)user_data;"
  , "    void *closure = data->closure;"
  , "    int nargs = data->nargs;"
  , ""
  , "    /* Load fnptr from closure[0] */"
  , "    void *fnptr = *(void **)closure;"
  , ""
  , "    /* Build pllisp args: [closure_ptr, arg0_as_pllisp_value, ...] */"
  , "    int total_args = nargs + 1;"
  , "    void *pll_arg_ptrs[total_args];"
  , "    pll_cb_value converted[nargs > 0 ? nargs : 1];"
  , "    pll_arg_ptrs[0] = &closure;"
  , "    for (int i = 0; i < nargs; i++) {"
  , "        switch (data->arg_types[i]) {"
  , "            case 0:  converted[i].i64 = (int64_t)*(int8_t *)args[i]; break;"
  , "            case 1:  converted[i].i64 = (int64_t)*(int16_t *)args[i]; break;"
  , "            case 2:  converted[i].i64 = (int64_t)*(int32_t *)args[i]; break;"
  , "            case 3:  converted[i].i64 = *(int64_t *)args[i]; break;"
  , "            case 4:  converted[i].i64 = (int64_t)*(uint8_t *)args[i]; break;"
  , "            case 5:  converted[i].i64 = (int64_t)*(uint16_t *)args[i]; break;"
  , "            case 6:  converted[i].i64 = (int64_t)*(uint32_t *)args[i]; break;"
  , "            case 7:  converted[i].i64 = (int64_t)*(uint64_t *)args[i]; break;"
  , "            case 8:  converted[i].f64 = (double)*(float *)args[i]; break;"
  , "            case 9:  converted[i].f64 = *(double *)args[i]; break;"
  , "            case 10: converted[i].ptr = *(void **)args[i]; break;"
  , "            default: converted[i].i64 = 0; break;"
  , "        }"
  , "        pll_arg_ptrs[i + 1] = &converted[i];"
  , "    }"
  , ""
  , "    /* Call pllisp function via libffi */"
  , "    pll_cb_value result;"
  , "    result.i64 = 0;"
  , "    ffi_call(&data->inner_cif, FFI_FN(fnptr), &result, pll_arg_ptrs);"
  , ""
  , "    /* Convert result back to C type */"
  , "    switch (data->ret_type) {"
  , "        case 0:  *(int8_t *)ret = (int8_t)result.i64; break;"
  , "        case 1:  *(int16_t *)ret = (int16_t)result.i64; break;"
  , "        case 2:  *(int32_t *)ret = (int32_t)result.i64; break;"
  , "        case 3:  *(int64_t *)ret = result.i64; break;"
  , "        case 4:  *(uint8_t *)ret = (uint8_t)result.i64; break;"
  , "        case 5:  *(uint16_t *)ret = (uint16_t)result.i64; break;"
  , "        case 6:  *(uint32_t *)ret = (uint32_t)result.i64; break;"
  , "        case 7:  *(uint64_t *)ret = (uint64_t)result.i64; break;"
  , "        case 8:  *(float *)ret = (float)result.f64; break;"
  , "        case 9:  *(double *)ret = result.f64; break;"
  , "        case 10: *(void **)ret = result.ptr; break;"
  , "        case 11: return;"
  , "        default: *(int64_t *)ret = result.i64; break;"
  , "    }"
  , "}"
  , ""
  , "void *pll_make_callback(void *closure, int nargs, int *arg_types, int ret_type) {"
  , "    /* Build outer CIF (what C callers see) */"
  , "    ffi_type **outer_atypes = malloc(sizeof(ffi_type*) * (nargs > 0 ? nargs : 1));"
  , "    for (int i = 0; i < nargs; i++)"
  , "        outer_atypes[i] = tag_to_ffi_type(arg_types[i]);"
  , "    ffi_type *outer_rtype = tag_to_ffi_type(ret_type);"
  , ""
  , "    ffi_cif *outer_cif = malloc(sizeof(ffi_cif));"
  , "    ffi_prep_cif(outer_cif, FFI_DEFAULT_ABI, (unsigned)nargs,"
  , "                 outer_rtype, nargs > 0 ? outer_atypes : NULL);"
  , ""
  , "    /* Build inner CIF (pllisp calling convention: ptr + pllisp args -> pllisp ret) */"
  , "    pll_cb_data *data = malloc(sizeof(pll_cb_data));"
  , "    data->closure = closure;"
  , "    data->nargs = nargs;"
  , "    data->arg_types = arg_types;"
  , "    data->ret_type = ret_type;"
  , ""
  , "    int inner_nargs = nargs + 1;"
  , "    ffi_type **inner_atypes = malloc(sizeof(ffi_type*) * inner_nargs);"
  , "    inner_atypes[0] = &ffi_type_pointer;"
  , "    for (int i = 0; i < nargs; i++)"
  , "        inner_atypes[i + 1] = pll_inner_ffi_type(arg_types[i]);"
  , "    ffi_prep_cif(&data->inner_cif, FFI_DEFAULT_ABI, (unsigned)inner_nargs,"
  , "                 pll_inner_ffi_type(ret_type), inner_atypes);"
  , ""
  , "    /* Allocate libffi closure */"
  , "    void *code_ptr;"
  , "    ffi_closure *ffi_cl = ffi_closure_alloc(sizeof(ffi_closure), &code_ptr);"
  , "    ffi_prep_closure_loc(ffi_cl, outer_cif, pll_cb_handler, data, code_ptr);"
  , "    return code_ptr;"
  , "}"
  , ""
  , "/* Test helper: apply a C function pointer (int64_t -> int64_t) */"
  , "int64_t pll_test_apply_int(void *fn, int64_t x) {"
  , "    typedef int64_t (*fn_t)(int64_t);"
  , "    return ((fn_t)fn)(x);"
  , "}"
  , ""
  , "double pll_test_apply_flt64(void *fn, double x) {"
  , "    typedef double (*fn_t)(double);"
  , "    return ((fn_t)fn)(x);"
  , "}"
  , ""
  , "float pll_test_apply_flt32(void *fn, float x) {"
  , "    typedef float (*fn_t)(float);"
  , "    return ((fn_t)fn)(x);"
  , "}"
  , ""
  , "double pll_test_apply_mix_num(void *fn, int64_t i, double x) {"
  , "    typedef double (*fn_t)(int64_t, double);"
  , "    return ((fn_t)fn)(i, x);"
  , "}"
  , ""
  , "/* Test helpers for struct by value */"
  , "typedef struct { int32_t x; int32_t y; } pll_point_t;"
  , ""
  , "int64_t pll_point_sum(void *p) {"
  , "    pll_point_t *pt = (pll_point_t *)p;"
  , "    return (int64_t)(pt->x + pt->y);"
  , "}"
  , ""
  , "void pll_point_scale(void *p, int64_t factor) {"
  , "    pll_point_t *pt = (pll_point_t *)p;"
  , "    pt->x *= (int32_t)factor;"
  , "    pt->y *= (int32_t)factor;"
  , "}"
  , ""
  , "/* FILEIO runtime helpers */"
  , "#define PLL_FILE_MODE_IN 1"
  , "#define PLL_FILE_MODE_OUT 2"
  , "#define PLL_FILE_MODE_APPEND 4"
  , "#define PLL_FILE_MAX_HANDLES 256"
  , ""
  , "typedef struct {"
  , "    FILE *fp;"
  , "    int mode;"
  , "} pll_file_handle;"
  , ""
  , "static pll_file_handle pll_file_handles[PLL_FILE_MAX_HANDLES];"
  , "static char pll_file_last_error_buf[512] = \"\";"
  , "static int64_t pll_file_last_status_flag = 1;"
  , "static int64_t pll_file_last_read_state = 0;"
  , "static int64_t pll_file_last_stat_kind_code = 0;"
  , "static int64_t pll_file_last_stat_size_value = 0;"
  , "static char **pll_file_last_dir_items = NULL;"
  , "static int64_t pll_file_last_dir_count = 0;"
  , ""
  , "static void pll_file_set_ok(void) {"
  , "    pll_file_last_status_flag = 1;"
  , "    pll_file_last_error_buf[0] = '\\0';"
  , "}"
  , ""
  , "static void pll_file_set_error_msg(const char *msg) {"
  , "    pll_file_last_status_flag = 0;"
  , "    snprintf(pll_file_last_error_buf, sizeof(pll_file_last_error_buf), \"%s\", msg);"
  , "}"
  , ""
  , "static void pll_file_set_errno_error(void) {"
  , "    pll_file_last_status_flag = 0;"
  , "    snprintf(pll_file_last_error_buf, sizeof(pll_file_last_error_buf), \"%s\", strerror(errno));"
  , "}"
  , ""
  , "static char *pll_gc_strdup(const char *src) {"
  , "    size_t len = strlen(src);"
  , "    char *dst = GC_malloc(len + 1);"
  , "    memcpy(dst, src, len + 1);"
  , "    return dst;"
  , "}"
  , ""
  , "static int pll_file_dirent_cmp(const void *lhs, const void *rhs) {"
  , "    const char *const *a = (const char *const *)lhs;"
  , "    const char *const *b = (const char *const *)rhs;"
  , "    return strcmp(*a, *b);"
  , "}"
  , ""
  , "static void pll_file_clear_dir_items(void) {"
  , "    if (pll_file_last_dir_items != NULL) {"
  , "        free(pll_file_last_dir_items);"
  , "        pll_file_last_dir_items = NULL;"
  , "    }"
  , "    pll_file_last_dir_count = 0;"
  , "}"
  , ""
  , "static int64_t pll_file_alloc_slot(FILE *fp, int mode) {"
  , "    for (int i = 0; i < PLL_FILE_MAX_HANDLES; i++) {"
  , "        if (pll_file_handles[i].fp == NULL) {"
  , "            pll_file_handles[i].fp = fp;"
  , "            pll_file_handles[i].mode = mode;"
  , "            return (int64_t)(i + 1);"
  , "        }"
  , "    }"
  , "    return 0;"
  , "}"
  , ""
  , "static pll_file_handle *pll_file_get_slot(int64_t token, int mode_mask, const char *mode_desc) {"
  , "    if (token < 1 || token > PLL_FILE_MAX_HANDLES) {"
  , "        pll_file_set_error_msg(\"invalid file handle\");"
  , "        return NULL;"
  , "    }"
  , "    pll_file_handle *slot = &pll_file_handles[token - 1];"
  , "    if (slot->fp == NULL) {"
  , "        pll_file_set_error_msg(\"invalid file handle\");"
  , "        return NULL;"
  , "    }"
  , "    if ((slot->mode & mode_mask) == 0) {"
  , "        if (mode_desc != NULL) {"
  , "            char buf[128];"
  , "            snprintf(buf, sizeof(buf), \"handle is not open for %s\", mode_desc);"
  , "            pll_file_set_error_msg(buf);"
  , "        } else {"
  , "            pll_file_set_error_msg(\"invalid file handle mode\");"
  , "        }"
  , "        return NULL;"
  , "    }"
  , "    return slot;"
  , "}"
  , ""
  , "int64_t pll_file_open_in(const char *path) {"
  , "    FILE *fp = fopen(path, \"r\");"
  , "    if (fp == NULL) {"
  , "        pll_file_set_errno_error();"
  , "        return 0;"
  , "    }"
  , "    int64_t token = pll_file_alloc_slot(fp, PLL_FILE_MODE_IN);"
  , "    if (token == 0) {"
  , "        fclose(fp);"
  , "        pll_file_set_error_msg(\"too many open files\");"
  , "        return 0;"
  , "    }"
  , "    pll_file_set_ok();"
  , "    return token;"
  , "}"
  , ""
  , "int64_t pll_file_open_out(const char *path) {"
  , "    FILE *fp = fopen(path, \"w\");"
  , "    if (fp == NULL) {"
  , "        pll_file_set_errno_error();"
  , "        return 0;"
  , "    }"
  , "    int64_t token = pll_file_alloc_slot(fp, PLL_FILE_MODE_OUT);"
  , "    if (token == 0) {"
  , "        fclose(fp);"
  , "        pll_file_set_error_msg(\"too many open files\");"
  , "        return 0;"
  , "    }"
  , "    pll_file_set_ok();"
  , "    return token;"
  , "}"
  , ""
  , "int64_t pll_file_open_append(const char *path) {"
  , "    FILE *fp = fopen(path, \"a\");"
  , "    if (fp == NULL) {"
  , "        pll_file_set_errno_error();"
  , "        return 0;"
  , "    }"
  , "    int64_t token = pll_file_alloc_slot(fp, PLL_FILE_MODE_APPEND);"
  , "    if (token == 0) {"
  , "        fclose(fp);"
  , "        pll_file_set_error_msg(\"too many open files\");"
  , "        return 0;"
  , "    }"
  , "    pll_file_set_ok();"
  , "    return token;"
  , "}"
  , ""
  , "int64_t pll_file_close(int64_t token) {"
  , "    pll_file_handle *slot = pll_file_get_slot(token, PLL_FILE_MODE_IN | PLL_FILE_MODE_OUT | PLL_FILE_MODE_APPEND, NULL);"
  , "    if (slot == NULL) {"
  , "        return 0;"
  , "    }"
  , "    FILE *fp = slot->fp;"
  , "    slot->fp = NULL;"
  , "    slot->mode = 0;"
  , "    if (fclose(fp) != 0) {"
  , "        pll_file_set_errno_error();"
  , "        return 0;"
  , "    }"
  , "    pll_file_set_ok();"
  , "    return 1;"
  , "}"
  , ""
  , "char *pll_file_read_line(int64_t token) {"
  , "    pll_file_handle *slot = pll_file_get_slot(token, PLL_FILE_MODE_IN, \"reading\");"
  , "    if (slot == NULL) {"
  , "        pll_file_last_read_state = 2;"
  , "        return pll_gc_strdup(\"\");"
  , "    }"
  , "    char *line = NULL;"
  , "    size_t cap = 0;"
  , "    ssize_t nread = getline(&line, &cap, slot->fp);"
  , "    if (nread < 0) {"
  , "        if (feof(slot->fp)) {"
  , "            pll_file_set_ok();"
  , "            pll_file_last_read_state = 1;"
  , "            free(line);"
  , "            return pll_gc_strdup(\"\");"
  , "        }"
  , "        pll_file_set_errno_error();"
  , "        pll_file_last_read_state = 2;"
  , "        free(line);"
  , "        return pll_gc_strdup(\"\");"
  , "    }"
  , "    if (nread > 0 && line[nread - 1] == '\\n') {"
  , "        line[nread - 1] = '\\0';"
  , "        nread--; "
  , "        if (nread > 0 && line[nread - 1] == '\\r') {"
  , "            line[nread - 1] = '\\0';"
  , "        }"
  , "    }"
  , "    char *copy = pll_gc_strdup(line);"
  , "    free(line);"
  , "    pll_file_set_ok();"
  , "    pll_file_last_read_state = 0;"
  , "    return copy;"
  , "}"
  , ""
  , "char *pll_file_read_all(int64_t token) {"
  , "    pll_file_handle *slot = pll_file_get_slot(token, PLL_FILE_MODE_IN, \"reading\");"
  , "    if (slot == NULL) {"
  , "        return pll_gc_strdup(\"\");"
  , "    }"
  , "    size_t cap = 4096;"
  , "    size_t len = 0;"
  , "    char *buf = malloc(cap);"
  , "    if (buf == NULL) {"
  , "        pll_file_set_error_msg(\"out of memory\");"
  , "        return pll_gc_strdup(\"\");"
  , "    }"
  , "    while (1) {"
  , "        char chunk[4096];"
  , "        size_t n = fread(chunk, 1, sizeof(chunk), slot->fp);"
  , "        if (n == 0) {"
  , "            break;"
  , "        }"
  , "        while (len + n + 1 > cap) {"
  , "            cap *= 2;"
  , "            char *next = realloc(buf, cap);"
  , "            if (next == NULL) {"
  , "                free(buf);"
  , "                pll_file_set_error_msg(\"out of memory\");"
  , "                return pll_gc_strdup(\"\");"
  , "            }"
  , "            buf = next;"
  , "        }"
  , "        memcpy(buf + len, chunk, n);"
  , "        len += n;"
  , "    }"
  , "    if (ferror(slot->fp)) {"
  , "        free(buf);"
  , "        pll_file_set_errno_error();"
  , "        return pll_gc_strdup(\"\");"
  , "    }"
  , "    buf[len] = '\\0';"
  , "    char *copy = pll_gc_strdup(buf);"
  , "    free(buf);"
  , "    pll_file_set_ok();"
  , "    return copy;"
  , "}"
  , ""
  , "int64_t pll_file_eof(int64_t token) {"
  , "    pll_file_handle *slot = pll_file_get_slot(token, PLL_FILE_MODE_IN, \"reading\");"
  , "    if (slot == NULL) {"
  , "        return -1;"
  , "    }"
  , "    if (ferror(slot->fp)) {"
  , "        pll_file_set_errno_error();"
  , "        return -1;"
  , "    }"
  , "    pll_file_set_ok();"
  , "    return feof(slot->fp) ? 1 : 0;"
  , "}"
  , ""
  , "int64_t pll_file_write(int64_t token, const char *text) {"
  , "    pll_file_handle *slot = pll_file_get_slot(token, PLL_FILE_MODE_OUT | PLL_FILE_MODE_APPEND, \"writing\");"
  , "    if (slot == NULL) {"
  , "        return 0;"
  , "    }"
  , "    size_t len = strlen(text);"
  , "    if (len > 0 && fwrite(text, 1, len, slot->fp) != len) {"
  , "        pll_file_set_errno_error();"
  , "        return 0;"
  , "    }"
  , "    pll_file_set_ok();"
  , "    return 1;"
  , "}"
  , ""
  , "int64_t pll_file_flush(int64_t token) {"
  , "    pll_file_handle *slot = pll_file_get_slot(token, PLL_FILE_MODE_OUT | PLL_FILE_MODE_APPEND, \"writing\");"
  , "    if (slot == NULL) {"
  , "        return 0;"
  , "    }"
  , "    if (fflush(slot->fp) != 0) {"
  , "        pll_file_set_errno_error();"
  , "        return 0;"
  , "    }"
  , "    pll_file_set_ok();"
  , "    return 1;"
  , "}"
  , ""
  , "const char *pll_file_last_error(void) {"
  , "    return pll_file_last_error_buf;"
  , "}"
  , ""
  , "int64_t pll_file_last_status(void) {"
  , "    return pll_file_last_status_flag;"
  , "}"
  , ""
  , "int64_t pll_file_read_status(void) {"
  , "    return pll_file_last_read_state;"
  , "}"
  , ""
  , "int64_t pll_file_exists(const char *path) {"
  , "    struct stat st;"
  , "    return stat(path, &st) == 0 ? 1 : 0;"
  , "}"
  , ""
  , "int64_t pll_file_is_file(const char *path) {"
  , "    struct stat st;"
  , "    return stat(path, &st) == 0 && S_ISREG(st.st_mode) ? 1 : 0;"
  , "}"
  , ""
  , "int64_t pll_file_is_dir(const char *path) {"
  , "    struct stat st;"
  , "    return stat(path, &st) == 0 && S_ISDIR(st.st_mode) ? 1 : 0;"
  , "}"
  , ""
  , "int64_t pll_file_stat(const char *path) {"
  , "    struct stat st;"
  , "    if (stat(path, &st) != 0) {"
  , "        pll_file_set_errno_error();"
  , "        return 0;"
  , "    }"
  , "    pll_file_last_stat_size_value = (int64_t)st.st_size;"
  , "    if (S_ISREG(st.st_mode)) {"
  , "        pll_file_last_stat_kind_code = 1;"
  , "    } else if (S_ISDIR(st.st_mode)) {"
  , "        pll_file_last_stat_kind_code = 2;"
  , "    } else {"
  , "        pll_file_last_stat_kind_code = 3;"
  , "    }"
  , "    pll_file_set_ok();"
  , "    return 1;"
  , "}"
  , ""
  , "int64_t pll_file_last_stat_kind(void) {"
  , "    return pll_file_last_stat_kind_code;"
  , "}"
  , ""
  , "int64_t pll_file_last_stat_size(void) {"
  , "    return pll_file_last_stat_size_value;"
  , "}"
  , ""
  , "int64_t pll_file_readdir_count(const char *path) {"
  , "    DIR *dir = opendir(path);"
  , "    pll_file_clear_dir_items();"
  , "    if (dir == NULL) {"
  , "        pll_file_set_errno_error();"
  , "        return -1;"
  , "    }"
  , "    size_t cap = 8;"
  , "    size_t count = 0;"
  , "    char **items = malloc(sizeof(char *) * cap);"
  , "    if (items == NULL) {"
  , "        closedir(dir);"
  , "        pll_file_set_error_msg(\"out of memory\");"
  , "        return -1;"
  , "    }"
  , "    struct dirent *entry;"
  , "    while ((entry = readdir(dir)) != NULL) {"
  , "        if (strcmp(entry->d_name, \".\") == 0 || strcmp(entry->d_name, \"..\") == 0) {"
  , "            continue;"
  , "        }"
  , "        if (count == cap) {"
  , "            cap *= 2;"
  , "            char **next = realloc(items, sizeof(char *) * cap);"
  , "            if (next == NULL) {"
  , "                free(items);"
  , "                closedir(dir);"
  , "                pll_file_set_error_msg(\"out of memory\");"
  , "                return -1;"
  , "            }"
  , "            items = next;"
  , "        }"
  , "        items[count++] = pll_gc_strdup(entry->d_name);"
  , "    }"
  , "    closedir(dir);"
  , "    qsort(items, count, sizeof(char *), pll_file_dirent_cmp);"
  , "    pll_file_last_dir_items = items;"
  , "    pll_file_last_dir_count = (int64_t)count;"
  , "    pll_file_set_ok();"
  , "    return (int64_t)count;"
  , "}"
  , ""
  , "const char *pll_file_readdir_item(int64_t idx) {"
  , "    if (idx < 0 || idx >= pll_file_last_dir_count || pll_file_last_dir_items == NULL) {"
  , "        return \"\";"
  , "    }"
  , "    return pll_file_last_dir_items[idx];"
  , "}"
  , ""
  , "int64_t pll_file_mkdir(const char *path) {"
  , "    if (mkdir(path, 0777) != 0) {"
  , "        pll_file_set_errno_error();"
  , "        return 0;"
  , "    }"
  , "    pll_file_set_ok();"
  , "    return 1;"
  , "}"
  , ""
  , "int64_t pll_file_mkdir_p(const char *path) {"
  , "    size_t len = strlen(path);"
  , "    if (len == 0) {"
  , "        pll_file_set_error_msg(\"empty path\");"
  , "        return 0;"
  , "    }"
  , "    if (len >= 4096) {"
  , "        pll_file_set_error_msg(\"path too long\");"
  , "        return 0;"
  , "    }"
  , "    char tmp[4096];"
  , "    memcpy(tmp, path, len + 1);"
  , "    for (char *p = tmp + 1; *p; p++) {"
  , "        if (*p == '/') {"
  , "            *p = '\\0';"
  , "            if (mkdir(tmp, 0777) != 0 && errno != EEXIST) {"
  , "                pll_file_set_errno_error();"
  , "                return 0;"
  , "            }"
  , "            *p = '/';"
  , "        }"
  , "    }"
  , "    if (mkdir(tmp, 0777) != 0 && errno != EEXIST) {"
  , "        pll_file_set_errno_error();"
  , "        return 0;"
  , "    }"
  , "    pll_file_set_ok();"
  , "    return 1;"
  , "}"
  , ""
  , "int64_t pll_file_unlink(const char *path) {"
  , "    if (unlink(path) != 0) {"
  , "        pll_file_set_errno_error();"
  , "        return 0;"
  , "    }"
  , "    pll_file_set_ok();"
  , "    return 1;"
  , "}"
  , ""
  , "int64_t pll_file_rename(const char *from, const char *to) {"
  , "    if (rename(from, to) != 0) {"
  , "        pll_file_set_errno_error();"
  , "        return 0;"
  , "    }"
  , "    pll_file_set_ok();"
  , "    return 1;"
  , "}"
  , ""
  , "int64_t pll_file_copy(const char *from, const char *to) {"
  , "    FILE *src = fopen(from, \"rb\");"
  , "    if (src == NULL) {"
  , "        pll_file_set_errno_error();"
  , "        return 0;"
  , "    }"
  , "    FILE *dst = fopen(to, \"wb\");"
  , "    if (dst == NULL) {"
  , "        fclose(src);"
  , "        pll_file_set_errno_error();"
  , "        return 0;"
  , "    }"
  , "    char buf[8192];"
  , "    while (1) {"
  , "        size_t n = fread(buf, 1, sizeof(buf), src);"
  , "        if (n == 0) {"
  , "            break;"
  , "        }"
  , "        if (fwrite(buf, 1, n, dst) != n) {"
  , "            fclose(src);"
  , "            fclose(dst);"
  , "            pll_file_set_errno_error();"
  , "            return 0;"
  , "        }"
  , "    }"
  , "    if (ferror(src)) {"
  , "        fclose(src);"
  , "        fclose(dst);"
  , "        pll_file_set_errno_error();"
  , "        return 0;"
  , "    }"
  , "    fclose(src);"
  , "    if (fclose(dst) != 0) {"
  , "        pll_file_set_errno_error();"
  , "        return 0;"
  , "    }"
  , "    pll_file_set_ok();"
  , "    return 1;"
  , "}"
  ]

-- The LLVM IR type string for a CType.
cTypeLlvm :: CType -> T.Text
cTypeLlvm CI8  = "i8"
cTypeLlvm CI16 = "i16"
cTypeLlvm CI32 = "i32"
cTypeLlvm CI64 = "i64"
cTypeLlvm CU8  = "i8"
cTypeLlvm CU16 = "i16"
cTypeLlvm CU32 = "i32"
cTypeLlvm CU64 = "i64"
cTypeLlvm CF32 = "float"
cTypeLlvm CF64 = "double"
cTypeLlvm CPtr = "ptr"
cTypeLlvm CVoid = "void"
cTypeLlvm (CArr _ _) = "ptr"   -- arrays accessed as pointers
cTypeLlvm (CStruct _) = "ptr"  -- nested structs stored as pointers

renderCType :: CType -> T.Text
renderCType ct = case ct of
  CI8 -> "%I8"
  CI16 -> "%I16"
  CI32 -> "%I32"
  CI64 -> "%I64"
  CU8 -> "%U8"
  CU16 -> "%U16"
  CU32 -> "%U32"
  CU64 -> "%U64"
  CF32 -> "%F32"
  CF64 -> "%F64"
  CPtr -> "%PTR"
  CVoid -> "%VOID"
  CArr n elemTy -> "(%ARR " <> T.pack (show n) <> " " <> renderCType elemTy <> ")"
  CStruct name -> "%" <> name

-- C struct layout computation: size, alignment, and field offsets.

cTypeSize :: CType -> Int
cTypeSize CI8  = 1
cTypeSize CI16 = 2
cTypeSize CI32 = 4
cTypeSize CI64 = 8
cTypeSize CU8  = 1
cTypeSize CU16 = 2
cTypeSize CU32 = 4
cTypeSize CU64 = 8
cTypeSize CF32 = 4
cTypeSize CF64 = 8
cTypeSize CPtr = 8
cTypeSize CVoid = 0
cTypeSize (CArr n ct) = n * cTypeSize ct
cTypeSize (CStruct _) = 8  -- fallback; use cTypeSizeWith for nested structs

cTypeAlign :: CType -> Int
cTypeAlign (CArr _ ct) = cTypeAlign ct  -- array alignment = element alignment
cTypeAlign (CStruct _) = 8  -- fallback; use cTypeAlignWith for nested structs
cTypeAlign ct = cTypeSize ct  -- on x86-64, alignment == size for all primitive types

-- Size/alignment with struct layout lookup
cTypeSizeWith :: M.Map T.Text StructLayout -> CType -> Int
cTypeSizeWith m (CStruct name) = case M.lookup name m of
  Just sl -> slSize sl
  Nothing -> 8
cTypeSizeWith _ ct = cTypeSize ct

cTypeAlignWith :: M.Map T.Text StructLayout -> CType -> Int
cTypeAlignWith m (CStruct name) = case M.lookup name m of
  Just sl -> if slSize sl == 0 then 1 else maximum [cTypeAlignWith m ct | (_, _, ct) <- slOffsets sl]
  Nothing -> 8
cTypeAlignWith _ (CArr _ ct) = cTypeAlign ct
cTypeAlignWith _ ct = cTypeSize ct

data StructLayout = StructLayout
  { slSize    :: !Int           -- total struct size (padded to alignment)
  , slOffsets :: [(T.Text, Int, CType)]  -- (field name, byte offset, field CType)
  } deriving (Show)

type StructMap = M.Map T.Text StructLayout

computeStructLayout :: [(T.Text, CType)] -> StructLayout
computeStructLayout = computeStructLayoutWith M.empty

computeStructLayoutWith :: StructMap -> [(T.Text, CType)] -> StructLayout
computeStructLayoutWith m fields =
  let (offsets, endOffset) = go 0 fields
      maxAlign = if null fields then 1 else maximum (map (cTypeAlignWith m . snd) fields)
      totalSize = alignUp endOffset maxAlign
  in StructLayout totalSize offsets
  where
    go offset [] = ([], offset)
    go offset ((name, ct):rest) =
      let a = cTypeAlignWith m ct
          aligned = alignUp offset a
          s = cTypeSizeWith m ct
          (rest', endOff) = go (aligned + s) rest
      in ((name, aligned, ct) : rest', endOff)
    alignUp n a = ((n + a - 1) `div` a) * a

renderType :: Type -> T.Text
renderType t = case t of
  TyInt      -> "%INT"
  TyFlt      -> "%FLT"
  TyStr      -> "%STR"
  TyBool     -> "%BOOL"
  TyUnit     -> "%UNIT"
  TyRx    -> "%RX"
  TyUSym  -> "%USYM"
  TySyntax -> "%SYNTAX"
  TyFun as r -> "%(-> " <> T.intercalate " " (map renderType (as ++ [r])) <> ")"
  TyCon s [] -> "%" <> s
  TyCon s ts -> "%(" <> s <> " " <> T.intercalate " " (map renderType ts) <> ")"
  TyApp f a  -> "%(" <> renderType f <> " " <> renderType a <> ")"
  TyVar n    -> "%t" <> T.pack (show n)
